"use strict";

// ===== 單字資料：依回分組（藍色字體）=====
// 第七～十回已完成（07:64字/48句 08:45字/45句 09:46字/46句 10:45字/45句）
const WORDS_BY_UNIT = {
  "07": [
    ["pace", "步調；踱步"],
    ["acceptance", "接受（名詞）"],
    ["accept", "接受（動詞）"],
    ["acceptable", "可接受的"],
    ["retain", "保留；保有"],
    ["maintain", "維持"],
    ["sustain", "維持（生命）"],
    ["detain", "扣留；拘留"],
    ["content", "滿足的；使滿足"],
    ["contented", "感到滿足的"],
    ["contentment", "知足；滿足"],
    ["discontent", "不滿意的"],
    ["abandon", "放棄；拋棄"],
    ["foundation", "地基；基金會"],
    ["founder", "創立者"],
    ["assembly", "集會；裝配"],
    ["assemble", "組裝；集合"],
    ["shelter", "庇護處；避難"],
    ["encounter", "不期而遇"],
    ["theme", "主題"],
    ["phenomenon", "現象"],
    ["phenomenal", "了不起的"],
    ["rural", "鄉村的"],
    ["liquor", "烈酒"],
    ["site", "地點；場所"],
    ["code", "密碼；規範"],
    ["lean", "斜靠；瘦的"],
    ["pursue", "追求（動詞）"],
    ["pursuit", "追求（名詞）"],
    ["academic", "學術的"],
    ["academy", "學院"],
    ["maximum", "最大量"],
    ["maximize", "使增至最大"],
    ["minimum", "最小量"],
    ["minimize", "使降至最低"],
    ["manufacture", "製造；生產"],
    ["manufacturer", "製造商"],
    ["produce", "生產（動詞）"],
    ["cooperate", "合作（動詞）"],
    ["cooperation", "合作（名詞）"],
    ["cooperative", "合作的"],
    ["overcome", "克服"],
    ["creation", "創造（名詞）"],
    ["creativity", "創造力"],
    ["tragedy", "悲劇"],
    ["tragic", "悲劇的"],
    ["comedy", "喜劇"],
    ["comedian", "喜劇演員"],
    ["commerce", "商業"],
    ["commercial", "商業的"],
    ["constitute", "構成"],
    ["constitution", "憲法"],
    ["constitutional", "憲法的"],
    ["numerous", "極多的"],
    ["plentiful", "許多的"],
    ["manual", "使用手冊；手工的"],
    ["quarrel", "爭吵"],
    ["squabble", "爭吵；口角"],
    ["argument", "爭執"],
    ["argue", "爭執；爭論"],
    ["renew", "更新（動詞）"],
    ["renewal", "更新（名詞）"],
    ["shade", "陰涼處；卷簾"],
    ["shady", "陰涼的"]
  ],
  "08": [
    ["prominent", "顯著的；突出的"],
    ["fundamental", "基本的；根本的"],
    ["concentrate", "專心；集中"],
    ["concentration", "專心；濃度"],
    ["incident", "事件"],
    ["precise", "精確的"],
    ["precisely", "精確地；恰好"],
    ["agreeable", "令人愉快的；適宜的"],
    ["convention", "大會；慣例"],
    ["conventional", "傳統的；慣例的"],
    ["elsewhere", "在別處"],
    ["percent", "百分之"],
    ["percentage", "百分比"],
    ["imply", "暗示；意味著"],
    ["chamber", "房間；議場"],
    ["sympathy", "同情"],
    ["sympathetic", "有同情心的"],
    ["absorb", "吸收；使全神貫注"],
    ["attach", "附上；貼上"],
    ["attachment", "附件；依戀"],
    ["deserve", "應得；值得"],
    ["spiritual", "精神的；心靈的"],
    ["definite", "明確的"],
    ["definitely", "肯定地；明確地"],
    ["resistance", "抵抗；阻力"],
    ["loan", "貸款；借出"],
    ["formation", "形成；編隊"],
    ["register", "登記；註冊"],
    ["registration", "登記；註冊"],
    ["accuse", "控告；指責"],
    ["consult", "商量；諮詢"],
    ["consultant", "顧問"],
    ["efficiency", "效率"],
    ["universal", "全球的；普遍的"],
    ["flee", "逃走；逃避"],
    ["install", "安裝"],
    ["isolate", "隔離；孤立"],
    ["isolated", "孤立的；隔離的"],
    ["isolation", "隔離；孤立"],
    ["route", "路線；途徑"],
    ["welfare", "福利；福祉"],
    ["appreciation", "感激；欣賞"],
    ["spark", "火花；引發"],
    ["fax", "傳真"],
    ["impression", "印象"]
  ],
  "09": [
    ["continuous", "連續的"],
    ["continuously", "連續地"],
    ["continual", "不斷的"],
    ["plot", "情節"],
    ["consume", "消耗"],
    ["consumer", "消費者"],
    ["crack", "裂縫"],
    ["invest", "投資"],
    ["investment", "投資"],
    ["investor", "投資者"],
    ["calculate", "計算"],
    ["calculation", "計算"],
    ["regulate", "調節"],
    ["regulation", "規章"],
    ["machinery", "機械"],
    ["mechanic", "機械師"],
    ["mechanical", "機械的"],
    ["witness", "證人"],
    ["prime", "主要的"],
    ["dominant", "主導的"],
    ["dominate", "支配"],
    ["satisfaction", "滿意"],
    ["dissatisfaction", "不滿"],
    ["interpret", "解釋"],
    ["translate", "翻譯"],
    ["translation", "翻譯"],
    ["translator", "翻譯者"],
    ["virtue", "美德"],
    ["permanent", "永久的"],
    ["transfer", "轉移"],
    ["regarding", "關於"],
    ["fort", "要塞"],
    ["reception", "接待"],
    ["genuine", "真實的"],
    ["authentic", "真實的"],
    ["indication", "指示"],
    ["laboratory", "實驗室"],
    ["horizon", "地平線"],
    ["primitive", "原始的"],
    ["severe", "嚴重的"],
    ["annoy", "惹惱"],
    ["annoyed", "惱怒的"],
    ["annoying", "惹人厭的"],
    ["millionaire", "億萬富翁"],
    ["category", "類別"],
    ["representation", "代表"]
  ],
  "10": [
    ["merit", "優點"],
    ["curve", "曲線"],
    ["license", "執照"],
    ["dignity", "尊嚴"],
    ["dignify", "使光榮"],
    ["differ", "不同"],
    ["limitation", "限制"],
    ["conscience", "良心"],
    ["lecture", "演講"],
    ["lecturer", "講師"],
    ["quilt", "被子"],
    ["disturb", "打擾"],
    ["disturbing", "令人不安的"],
    ["aspirin", "阿司匹林"],
    ["predict", "預測"],
    ["prediction", "預測"],
    ["forecast", "預報"],
    ["cease", "停止"],
    ["ceasefire", "停火"],
    ["opera", "歌劇"],
    ["ballet", "芭蕾舞"],
    ["gallery", "畫廊"],
    ["restriction", "限制"],
    ["enforce", "執行"],
    ["enforcement", "執行"],
    ["complicate", "複雜化"],
    ["complicated", "複雜的"],
    ["era", "時代"],
    ["dependent", "依賴的"],
    ["dependence", "依賴"],
    ["dependable", "可靠的"],
    ["frequency", "頻率"],
    ["logic", "邏輯"],
    ["logical", "合乎邏輯的"],
    ["illogical", "不合邏輯的"],
    ["presentation", "演示"],
    ["admission", "入場券"],
    ["guilt", "罪惡感"],
    ["guilty", "有罪的"],
    ["reform", "改革"],
    ["household", "家庭"],
    ["housework", "家務"],
    ["celebration", "慶祝"],
    ["issue", "事項"],
    ["lengthen", "延長"]
  ]
};

const SENTENCES_BY_UNIT = {
  "07": [
    { s: "Duncan likes the fast {blank} of life in the city.", blank: "pace", base: "pace", zh: "鄧肯喜歡城市快速的生活步調。" },
    { s: "Dad {blank} the floor as he waited for his daughter to give birth to his first grandchild.", blank: "paced", base: "pace", zh: "爸爸等候女兒生下他頭一個金孫時，一直來回踱步。" },
    { s: "The new student found it hard to gain the {blank} of others.", blank: "acceptance", base: "acceptance", zh: "新來的學生發現要被其他同學接納並不容易。" },
    { s: "You'd better {blank} copies of the documents for at least one year.", blank: "retain", base: "retain", zh: "這些文件你最好留著至少一年別丟。" },
    { s: "The boxer succeeded in {blank} his title as the heavyweight champion.", blank: "retaining", base: "retain", zh: "那位拳擊手成功地衛冕重量級冠軍。" },
    { s: "Alex was {blank} with his performance in the speech contest.", blank: "content", base: "content", zh: "亞歷克斯對他在演講比賽的表現很滿意。" },
    { s: "The manager {blank} the plan to set up a new factory in Mexico.", blank: "abandoned", base: "abandon", zh: "經理放棄在墨西哥建立新廠的計畫。" },
    { s: "The workers laid the {blank} before they built the walls.", blank: "foundation", base: "foundation", zh: "工人們打好地基，然後把牆砌起來。" },
    { s: "George has a solid {blank} in geography.", blank: "foundation", base: "foundation", zh: "喬治在地理學方面有很好的基礎。" },
    { s: "If you know how to {blank} the computer yourself, you can save lots of money.", blank: "assemble", base: "assemble", zh: "你若懂得組裝電腦，便可以省下很多錢。" },
    { s: "The boy can take the parts apart, but he can't {blank} them.", blank: "assemble", base: "assemble", zh: "這個小男孩懂得把零件分解，卻無法將它們組合起來。" },
    { s: "The elderly people {blank} in the hospital for free flu shots.", blank: "assembled", base: "assemble", zh: "老人們聚集在醫院裡打免費的流感疫苗。" },
    { s: "It's against the law to {blank} a criminal from the police.", blank: "shelter", base: "shelter", zh: "庇護罪犯躲避警方是違法的。" },
    { s: "The homeless man needed a {blank} from the cold rain.", blank: "shelter", base: "shelter", zh: "那個無家可歸的人需要一個躲避寒雨的庇護處。" },
    { s: "I had an unexpected {blank} with my old friend in the supermarket.", blank: "encounter", base: "encounter", zh: "我在超市和老友不期而遇。" },
    { s: "We went to a famous {blank} park during the summer vacation.", blank: "theme", base: "theme", zh: "暑假我們去了著名的主題公園。" },
    { s: "Violence is not a new {blank} in Taiwan.", blank: "phenomenon", base: "phenomenon", zh: "暴力在臺灣不是個新現象。" },
    { s: "Some people prefer {blank} areas for a quiet environment.", blank: "rural", base: "rural", zh: "有些人因為環境安靜而喜歡住鄉下。" },
    { s: "You have to be 18 to drink {blank} in Taiwan.", blank: "liquor", base: "liquor", zh: "在臺灣你必須年滿 18 歲才能喝酒。" },
    { s: "There were several people at the {blank} of the accident helping the survivors.", blank: "site", base: "site", zh: "意外現場有幾個人幫忙生還者。" },
    { s: "You have to obey the dress {blank} if you want to work here.", blank: "code", base: "code", zh: "如果你想在這裡工作，就必須遵守服裝規定。" },
    { s: "Each word on the list is {blank} to show the level of difficulty.", blank: "coded", base: "code", zh: "表上的所有字都加以編碼，以顯示其難度。" },
    { s: "The young man was {blank} against the wall, looking at the sky.", blank: "leaning", base: "lean", zh: "這年輕人斜靠著牆，仰望著天空。" },
    { s: "You should eat more vegetables and {blank} meat if you want to slim down.", blank: "lean", base: "lean", zh: "如果你想瘦下來就應該多吃青菜及瘦肉。" },
    { s: "With my father's support, I have been able to {blank} my dreams.", blank: "pursue", base: "pursue", zh: "有了我爸的支持，我才能夠去追尋我的夢想。" },
    { s: "Peter is planning to study abroad in {blank} of a bright future.", blank: "pursuit", base: "pursuit", zh: "彼得計畫要出國留學，以追求光明的前途。" },
    { s: "Laziness may be responsible for Timmy's bad {blank} performance.", blank: "academic", base: "academic", zh: "懶惰或許是提米學業成績不佳的原因。" },
    { s: "Give yourself a {blank} of 20 minutes to read the questions.", blank: "maximum", base: "maximum", zh: "給自己最多 20 分鐘的時間讀完題目。" },
    { s: "You must practice playing the piano for a {blank} of two hours every day.", blank: "minimum", base: "minimum", zh: "你每天必須練習彈鋼琴至少兩個小時。" },
    { s: "Our company {blank} electronic devices.", blank: "manufactures", base: "manufacture", zh: "我們公司生產電子儀器。" },
    { s: "The {blank} of newspapers requires a lot of wood pulp.", blank: "manufacture", base: "manufacture", zh: "製造報紙需要許多木漿。" },
    { s: "We {blank} with the police to locate the suspects.", blank: "cooperated", base: "cooperate", zh: "我們和警方合作找出嫌疑犯。" },
    { s: "I could not {blank} the difficulty of learning French, so I changed my major.", blank: "overcome", base: "overcome", zh: "我無法克服學法文的困難，因此我換了主修科系。" },
    { s: "This project will help foster the {blank} of new jobs.", blank: "creation", base: "creation", zh: "本計畫將有助於創造新的就業機會。" },
    { s: "Without {blank}, one can't be a successful artist.", blank: "creativity", base: "creativity", zh: "一個人若是缺乏創意，就沒辦法成為成功的藝術家。" },
    { s: "Jason's death was a {blank} to his family.", blank: "tragedy", base: "tragedy", zh: "傑森的死對他的家庭是一個慘劇。" },
    { s: "I prefer comedies to {blank}.", blank: "tragedies", base: "tragedy", zh: "我喜歡看喜劇勝於悲劇。" },
    { s: "The Taming of the Shrew is one of Shakespeare's most famous {blank}.", blank: "comedies", base: "comedy", zh: "《馴悍記》是莎士比亞最著名的喜劇之一。" },
    { s: "Taipei is Taiwan's center of {blank}.", blank: "commerce", base: "commerce", zh: "台北是臺灣的商業中心。" },
    { s: "According to the US {blank}, people have the right to speak freely.", blank: "Constitution", base: "constitution", zh: "根據美國憲法，人民享有言論自由權。" },
    { s: "Seven days {blank} a week.", blank: "constitute", base: "constitute", zh: "七天構成一個星期。" },
    { s: "She has made {blank} contributions to the project.", blank: "numerous", base: "numerous", zh: "她對這個專案做了許多貢獻。" },
    { s: "You should read the {blank} before you use the copier.", blank: "manual", base: "manual", zh: "在使用這部影印機之前，你應該先閱讀使用手冊。" },
    { s: "Mark doesn't like {blank} labor. He wants a desk job instead.", blank: "manual", base: "manual", zh: "馬克不喜歡勞力工作。他反而想要一份坐辦公室的工作。" },
    { s: "Terence is ill-tempered. He {blank} with his wife over almost everything.", blank: "quarrels", base: "quarrel", zh: "泰倫斯的脾氣不好。他幾乎每件事都會和太太爭吵。" },
    { s: "The boss decided to {blank} my contract for another year.", blank: "renew", base: "renew", zh: "老闆決定將與我續簽一年的合約。" },
    { s: "We took a rest in the {blank} of a large tree.", blank: "shade", base: "shade", zh: "我們在一棵大樹的樹蔭下休息。" },
    { s: "Monica's beauty and confidence put other contestants in the {blank}.", blank: "shade", base: "shade", zh: "莫妮卡的美貌和自信使其他參賽者相形失色。" }
  ],
  "08": [
    { s: "She is a {blank} scholar in the field of AI.", blank: "prominent", base: "prominent", zh: "她是AI領域中一位傑出的學者。" },
    { s: "Math is a {blank} subject for engineering students.", blank: "fundamental", base: "fundamental", zh: "數學是工程系學生的基本科目。" },
    { s: "Please {blank} on your work and avoid distractions.", blank: "concentrate", base: "concentrate", zh: "請專心工作，避免分心。" },
    { s: "The {blank} of caffeine in this coffee is very high.", blank: "concentration", base: "concentration", zh: "這杯咖啡的咖啡因濃度非常高。" },
    { s: "A strange {blank} happened on the way to school.", blank: "incident", base: "incident", zh: "上學途中發生了一件奇怪的事件。" },
    { s: "The watch is {blank} to the second.", blank: "precise", base: "precise", zh: "這隻手錶精確到秒。" },
    { s: "The meeting ends at {blank} three o'clock.", blank: "precisely", base: "precisely", zh: "會議恰好三點結束。" },
    { s: "The weather is very {blank} for a picnic.", blank: "agreeable", base: "agreeable", zh: "這個天氣非常適合野餐。" },
    { s: "The annual teachers' {blank} will be held next week.", blank: "convention", base: "convention", zh: "一年一度的教師大會將在下週舉行。" },
    { s: "Most people still prefer {blank} paper books.", blank: "conventional", base: "conventional", zh: "大多數人仍然偏好傳統的紙本書。" },
    { s: "If you don't like it here, you can go {blank}.", blank: "elsewhere", base: "elsewhere", zh: "如果你不喜歡這裡，可以去別的地方。" },
    { s: "About 60 {blank} of students passed the exam.", blank: "percent", base: "percent", zh: "大約百分之六十的學生通過了考試。" },
    { s: "What {blank} of the budget is spent on food?", blank: "percentage", base: "percentage", zh: "預算的多少百分比用在食物上？" },
    { s: "Are you {blank} that you locked the door?", blank: "imply", base: "imply", zh: "你是在暗示你鎖了門嗎？" },
    { s: "The meeting {blank} was packed with attendees.", blank: "chamber", base: "chamber", zh: "會議廳擠滿了與會者。" },
    { s: "I feel deep {blank} for the victims of the disaster.", blank: "sympathy", base: "sympathy", zh: "我對災難的受害者深感同情。" },
    { s: "She is very {blank} and always listens to others.", blank: "sympathetic", base: "sympathetic", zh: "她非常有同情心，總是傾聽別人。" },
    { s: "The sponge can {blank} a lot of water.", blank: "absorb", base: "absorb", zh: "海綿可以吸收大量水分。" },
    { s: "Please {blank} a photo to your email.", blank: "attach", base: "attach", zh: "請在電子郵件中附加一張照片。" },
    { s: "I found an {blank} in the envelope but no letter.", blank: "attachment", base: "attachment", zh: "我在信封裡找到附件，但沒有信。" },
    { s: "Hard work {blank} a good result.", blank: "deserve", base: "deserve", zh: "努力工作值得好的結果。" },
    { s: "Music can heal our {blank} wounds.", blank: "spiritual", base: "spiritual", zh: "音樂能治癒我們心靈的創傷。" },
    { s: "Is there a {blank} answer to this question?", blank: "definite", base: "definite", zh: "這個問題有明確的答案嗎？" },
    { s: "I will {blank} be there on time.", blank: "definitely", base: "definitely", zh: "我一定會準時到達。" },
    { s: "The army met strong {blank} from the enemy.", blank: "resistance", base: "resistance", zh: "軍隊遭到敵人的激烈抵抗。" },
    { s: "Can I get a {blank} to buy a new computer?", blank: "loan", base: "loan", zh: "我能貸款買新電腦嗎？" },
    { s: "The {blank} of clouds brought rain.", blank: "formation", base: "formation", zh: "雲的形成了帶來了雨水。" },
    { s: "You need to {blank} before you can vote.", blank: "register", base: "register", zh: "你需要登記才能投票。" },
    { s: "Online {blank} for the course is now open.", blank: "registration", base: "registration", zh: "這門課的線上報名已經開放。" },
    { s: "The police {blank} him of stealing the car.", blank: "accuse", base: "accuse", zh: "警方指控他偷車。" },
    { s: "You should {blank} a doctor about your symptoms.", blank: "consult", base: "consult", zh: "你應該就你的症狀諮詢醫生。" },
    { s: "Our company hired a financial {blank}.", blank: "consultant", base: "consultant", zh: "我們公司聘請了一位財務顧問。" },
    { s: "This machine improves work {blank}.", blank: "efficiency", base: "efficiency", zh: "這台機器提高了工作效率。" },
    { s: "English is a {blank} language spoken worldwide.", blank: "universal", base: "universal", zh: "英語是全球通用的語言。" },
    { s: "The thief tried to {blank} from the police.", blank: "flee", base: "flee", zh: "小偷試圖逃離警方。" },
    { s: "They plan to {blank} solar panels on the roof.", blank: "install", base: "install", zh: "他們計畫在屋頂安裝太陽能板。" },
    { s: "The village was {blank} by the heavy snow.", blank: "isolated", base: "isolate", zh: "這個村莊被大雪隔離了。" },
    { s: "He felt {blank} and alone in the new city.", blank: "isolated", base: "isolate", zh: "他在新城市感到孤立無援。" },
    { s: "The patient was kept in {blank} to prevent infection.", blank: "isolation", base: "isolation", zh: "病人被隔離以防止感染。" },
    { s: "Follow this {blank} to reach the hospital.", blank: "route", base: "route", zh: "跟著這條路線就能到達醫院。" },
    { s: "The government provides {blank} for elderly citizens.", blank: "welfare", base: "welfare", zh: "政府為老年公民提供福利。" },
    { s: "She showed great {blank} for your help.", blank: "appreciation", base: "appreciation", zh: "她對你的幫助表示極大的感激。" },
    { s: "A single {blank} can start a forest fire.", blank: "spark", base: "spark", zh: "一粒火花就能引起森林大火。" },
    { s: "Please send the documents by {blank}.", blank: "fax", base: "fax", zh: "請用傳真發送文件。" },
    { s: "My first {blank} of him was very positive.", blank: "impression", base: "impression", zh: "我對他的第一印象非常正面。" }
  ],
  "09": [
    { s: "The rain fell in a {blank} rhythm all night.", blank: "continuous", base: "continuous", zh: "雨整晚以連續的節奏下著。" },
    { s: "She practices the piano {blank} to improve her skill.", blank: "continuously", base: "continuously", zh: "她持續不斷地練習鋼琴，以提升技巧。" },
    { s: "The school has a {blank} need for new textbooks each year.", blank: "continual", base: "continual", zh: "學校每年都有持續的需求，需要新課本。" },
    { s: "The detective tried to solve the mysterious {blank} of the missing book.", blank: "plot", base: "plot", zh: "偵探試圖解開失蹤書本的神祕情節。" },
    { s: "Plants {blank} sunlight and water to grow.", blank: "consume", base: "consume", zh: "植物需要光和水才能生長。" },
    { s: "Every {blank} has the right to choose what to buy.", blank: "consumer", base: "consumer", zh: "每位消費者都有選擇購買的權利。" },
    { s: "He heard a loud {blank} when the vase fell on the floor.", blank: "crack", base: "crack", zh: "當花瓶掉在地板上時，他聽到一聲巨響。" },
    { s: "They decided to {blank} money in a savings account.", blank: "invest", base: "invest", zh: "他們決定把錢投資到儲蓄帳戶。" },
    { s: "Her first {blank} in stocks earned a small profit.", blank: "investment", base: "investment", zh: "她首次的股票投資獲得了一點利潤。" },
    { s: "The {blank} bought shares of the new tech company.", blank: "investor", base: "investor", zh: "投資者購買了新科技公司的股份。" },
    { s: "You can {blank} the total cost by adding the prices together.", blank: "calculate", base: "calculate", zh: "你可以把價格相加來計算總成本。" },
    { s: "The teacher checked his math {blank} for mistakes.", blank: "calculation", base: "calculation", zh: "老師檢查了他的數學計算是否有錯誤。" },
    { s: "The government will {blank} the water quality to keep it safe.", blank: "regulate", base: "regulate", zh: "政府將調節水質以確保安全。" },
    { s: "New traffic {blank} require drivers to wear seat belts.", blank: "regulation", base: "regulation", zh: "新的交通規則要求駕駛員必須繫安全帶。" },
    { s: "The factory uses heavy {blank} to make metal parts.", blank: "machinery", base: "machinery", zh: "工廠使用重型機械來製造金屬零件。" },
    { s: "A {blank} fixed the broken bike chain after school.", blank: "mechanic", base: "mechanic", zh: "一位機械師在放學後修好了破損的自行車鏈條。" },
    { s: "The robot works by {blank} parts that move together.", blank: "mechanical", base: "mechanical", zh: "這個機器人透過機械部件協同運作。" },
    { s: "She was a {blank} to the accident and gave a clear statement.", blank: "witness", base: "witness", zh: "她是事故的目擊者，並提供了清晰的陳述。" },
    { s: "He is the {blank} suspect in the case, according to the police.", blank: "prime", base: "prime", zh: "根據警方說法，他是此案的主要嫌疑人。" },
    { s: "The lion is the {blank} animal in the savanna.", blank: "dominant", base: "dominant", zh: "獅子是草原上占主導地位的動物。" },
    { s: "The team hopes to {blank} the competition with their new strategy.", blank: "dominate", base: "dominate", zh: "團隊希望以新策略在比賽中佔上風。" },
    { s: "She felt great {blank} after finishing her project.", blank: "satisfaction", base: "satisfaction", zh: "完成專案後，她感到非常滿足。" },
    { s: "His {blank} with the cafeteria food made him skip lunch.", blank: "dissatisfaction", base: "dissatisfaction", zh: "他對學校餐廳食物的不滿讓他不吃午餐。" },
    { s: "The teacher asked us to {blank} the poem's meaning.", blank: "interpret", base: "interpret", zh: "老師請我們解釋這首詩的意涵。" },
    { s: "He can {blank} English sentences into Chinese quickly.", blank: "translate", base: "translate", zh: "他能快速把英文句子翻譯成中文。" },
    { s: "The book includes a French {blank} of the original story.", blank: "translation", base: "translation", zh: "這本書包含原作的法文翻譯。" },
    { s: "A professional {blank} helped the tourists understand the signs.", blank: "translator", base: "translator", zh: "專業翻譯員幫助遊客了解標示。" },
    { s: "Honesty is a {blank} that many people admire.", blank: "virtue", base: "virtue", zh: "誠實是一種許多人欣賞的美德。" },
    { s: "The museum displays a {blank} exhibit of ancient tools.", blank: "permanent", base: "permanent", zh: "博物館展示了一個永久性的古代工具展覽。" },
    { s: "Please {blank} the files to the new folder.", blank: "transfer", base: "transfer", zh: "請把檔案轉移到新資料夾。" },
    { s: "The email contains information {blank} the upcoming trip.", blank: "regarding", base: "regarding", zh: "這封電子郵件包含關於即將出發的旅行的資訊。" },
    { s: "The old {blank} on the hill was built centuries ago.", blank: "fort", base: "fort", zh: "山丘上的古老堡壘是幾個世紀前建造的。" },
    { s: "The hotel {blank} was decorated with balloons for the party.", blank: "reception", base: "reception", zh: "飯店的接待大廳為派對裝飾了氣球。" },
    { s: "Her smile looked {blank} and warm.", blank: "genuine", base: "genuine", zh: "她的笑容看起來真誠而溫暖。" },
    { s: "The artifact is {blank} and dates back to the Ming dynasty.", blank: "authentic", base: "authentic", zh: "這件文物是真品，追溯到明朝。" },
    { s: "A sudden headache can be an {blank} of stress.", blank: "indication", base: "indication", zh: "突如其來的頭痛可能是壓力的徵兆。" },
    { s: "Scientists work in a {blank} to test new chemicals.", blank: "laboratory", base: "laboratory", zh: "科學家在實驗室裡測試新化學物質。" },
    { s: "The sun set beyond the distant {blank}.", blank: "horizon", base: "horizon", zh: "太陽在遙遠的地平線之外落下。" },
    { s: "Cave paintings show {blank} ways of life from thousands of years ago.", blank: "primitive", base: "primitive", zh: "洞穴壁畫展示了數千年前原始的生活方式。" },
    { s: "The storm caused {blank} damage to the coastal town.", blank: "severe", base: "severe", zh: "暴風雨對沿海小鎮造成了嚴重的破壞。" },
    { s: "Loud chewing can {blank} some people during class.", blank: "annoy", base: "annoy", zh: "大聲咀嚼會讓一些人在課堂上感到惱火。" },
    { s: "She felt {blank} when her brother borrowed her bike without asking.", blank: "annoyed", base: "annoyed", zh: "當她的哥哥未經允許借走她的自行車時，她感到惱怒。" },
    { s: "The buzzing fly was very {blank} in the quiet library.", blank: "annoying", base: "annoying", zh: "嗡嗡叫的蒼蠅在寧靜的圖書館裡非常惹人厭煩。" },
    { s: "The charity event was attended by a local {blank} who donated a large sum.", blank: "millionaire", base: "millionaire", zh: "慈善活動有一位當地百萬富翁出席，捐贈了大筆金額。" },
    { s: "Animals are grouped into different {blank} such as mammals and birds.", blank: "category", base: "category", zh: "動物被分成不同的類別，例如哺乳動物和鳥類。" },
    { s: "The flag is a {blank} of the country's history and values.", blank: "representation", base: "representation", zh: "旗幟是該國歷史與價值觀的象徵。" }
  ],
  "10": [
    { s: "She earned a {blank} for her hard work.", blank: "merit", base: "merit", zh: "她因努力而獲得了功勞。" },
    { s: "The road makes a sharp {blank} near the hill.", blank: "curve", base: "curve", zh: "道路在山坡附近有一個急彎。" },
    { s: "You need a {blank} to drive a car.", blank: "license", base: "license", zh: "開車需要執照。" },
    { s: "She kept her {blank} even when she lost the game.", blank: "dignity", base: "dignity", zh: "即使輸了比賽，她仍保持尊嚴。" },
    { s: "He tried to {blank} his older brother by speaking politely.", blank: "dignify", base: "dignify", zh: "他試著用禮貌的說話方式使哥哥受尊敬。" },
    { s: "My answer will {blank} from yours.", blank: "differ", base: "differ", zh: "我的答案會和你的不同。" },
    { s: "There is a {blank} on how many books you can borrow.", blank: "limitation", base: "limitation", zh: "借書的數量有限制。" },
    { s: "His {blank} told him not to cheat.", blank: "conscience", base: "conscience", zh: "他的良心告訴他不要作弊。" },
    { s: "The teacher gave a short {blank} about planets.", blank: "lecture", base: "lecture", zh: "老師做了一個關於行星的短講。" },
    { s: "Our {blank} is very friendly and explains everything clearly.", blank: "lecturer", base: "lecturer", zh: "我們的講師非常友善，說明也很清楚。" },
    { s: "She made a warm {blank} for winter.", blank: "quilt", base: "quilt", zh: "她為冬天縫了一條暖和的被子。" },
    { s: "Please do not {blank} the sleeping baby.", blank: "disturb", base: "disturb", zh: "請不要打擾正在睡覺的嬰兒。" },
    { s: "The news story was very {blank}.", blank: "disturbing", base: "disturbing", zh: "那則新聞非常令人不安。" },
    { s: "He took an {blank} for his headache.", blank: "aspirin", base: "aspirin", zh: "他服用了一顆阿司匹林止痛。" },
    { s: "Scientists try to {blank} the weather for next week.", blank: "predict", base: "predict", zh: "科學家試圖預測下週的天氣。" },
    { s: "Her {blank} about the rain came true.", blank: "prediction", base: "prediction", zh: "她對雨的預測成真了。" },
    { s: "The weather {blank} says it will be sunny tomorrow.", blank: "forecast", base: "forecast", zh: "天氣預報說明天會是晴天。" },
    { s: "The fighting will {blank} tomorrow morning.", blank: "cease", base: "cease", zh: "戰鬥將於明早停止。" },
    { s: "A {blank} was signed after the war ended.", blank: "ceasefire", base: "ceasefire", zh: "戰爭結束後簽署了停火協議。" },
    { s: "We watched an {blank} about a brave queen.", blank: "opera", base: "opera", zh: "我們觀看了一部關於勇敢女王的歌劇。" },
    { s: "She practices {blank} every Thursday after school.", blank: "ballet", base: "ballet", zh: "她每週四放學後練習芭蕾舞。" },
    { s: "The new art {blank} opened downtown last month.", blank: "gallery", base: "gallery", zh: "新的藝術畫廊上個月在市中心開幕。" },
    { s: "There is a {blank} on loud music after 10 p.m.", blank: "restriction", base: "restriction", zh: "晚上十點後對大聲音樂有限制。" },
    { s: "Police {blank} the new traffic rules strictly.", blank: "enforce", base: "enforce", zh: "警察嚴格執行新的交通規則。" },
    { s: "The {blank} of the law keeps everyone safe.", blank: "enforcement", base: "enforcement", zh: "法律的執行讓大家都安全。" },
    { s: "Adding more steps will only {blank} the game.", blank: "complicate", base: "complicate", zh: "增加更多步驟只會讓遊戲變得更複雜。" },
    { s: "The math problem is very {blank} for most students.", blank: "complicated", base: "complicated", zh: "這道數學題對大多數學生來說非常複雜。" },
    { s: "The dinosaur {blank} ended millions of years ago.", blank: "era", base: "era", zh: "恐龍時代在數百萬年前結束。" },
    { s: "He is {blank} on his parents for financial support.", blank: "dependent", base: "dependent", zh: "他在經濟上依賴父母。" },
    { s: "Her {blank} on coffee makes her feel jittery.", blank: "dependence", base: "dependence", zh: "她對咖啡的依賴讓她感到坐立不安。" },
    { s: "A {blank} friend always keeps his promises.", blank: "dependable", base: "dependable", zh: "一個可靠的朋友總是遵守承諾。" },
    { s: "The {blank} of buses is every ten minutes during rush hour.", blank: "frequency", base: "frequency", zh: "高峰時段公車的班次頻率是每十分鐘一班。" },
    { s: "Good {blank} helps you solve puzzles quickly.", blank: "logic", base: "logic", zh: "良好的邏輯能幫助你快速解謎。" },
    { s: "It is {blank} to wear a coat when it is cold outside.", blank: "logical", base: "logical", zh: "在外面很冷時穿外套是合乎邏輯的。" },
    { s: "It is {blank} to think the sun will rise at night.", blank: "illogical", base: "illogical", zh: "認為太陽會在夜裡升起是沒有邏輯的。" },
    { s: "She prepared a {blank} about the solar system for class.", blank: "presentation", base: "presentation", zh: "她為班上準備了一個關於太陽系的簡報。" },
    { s: "His {blank} to the school was celebrated by his family.", blank: "admission", base: "admission", zh: "他被錄取的消息讓家人很高興。" },
    { s: "She felt {blank} after breaking her friend's toy.", blank: "guilt", base: "guilt", zh: "她打破朋友的玩具後感到內疚。" },
    { s: "He was found {blank} of stealing the bike.", blank: "guilty", base: "guilty", zh: "他被判定偷自行車有罪。" },
    { s: "The school plans to {blank} its rules to be fairer.", blank: "reform", base: "reform", zh: "學校計畫改革規則，使之更公平。" },
    { s: "Cleaning the kitchen is a {blank} chore for the whole family.", blank: "household", base: "household", zh: "打掃廚房是全家共同的家務。" },
    { s: "She helps with {blank} after school every day.", blank: "housework", base: "housework", zh: "她每天放學後幫忙做家務。" },
    { s: "The birthday {blank} was full of balloons and cake.", blank: "celebration", base: "celebration", zh: "生日慶祝活動充滿了氣球和蛋糕。" },
    { s: "The main {blank} we need to solve is the water shortage.", blank: "issue", base: "issue", zh: "我們需要解決的主要問題是缺水。" },
    { s: "We can {blank} the break by ten minutes if everyone agrees.", blank: "lengthen", base: "lengthen", zh: "如果大家同意，我們可以把休息時間延長十分鐘。" }
  ]
};

// 相容舊版：全部合併（供未選範圍時使用）
const WORDS = Object.values(WORDS_BY_UNIT).flat();
const SENTENCES = Object.values(SENTENCES_BY_UNIT).flat();
