"use strict";

// ===== 單字資料（主單字＋衍生字）：[英文, 中文] =====
const WORDS = [
  ["pace", "步調；踱步"],
  ["acceptance", "接受（名詞）"],
  ["accept", "接受（動詞）"],
  ["acceptable", "可接受的"],
  ["retain", "保留；保有"],
  ["maintain", "維持"],
  ["sustain", "維持（生命）"],
  ["detain", "扣留；拘留"],
  ["content", "滿足的；使滿足"],
  ["contented", "感到滿足的"],
  ["contentment", "知足；滿足"],
  ["discontent", "不滿意的"],
  ["abandon", "放棄；拋棄"],
  ["foundation", "地基；基金會"],
  ["found", "建立；創立"],
  ["founder", "創立者"],
  ["assembly", "集會；裝配"],
  ["assemble", "組裝；集合"],
  ["disassemble", "分解"],
  ["shelter", "庇護處；避難"],
  ["encounter", "不期而遇"],
  ["theme", "主題"],
  ["phenomenon", "現象"],
  ["phenomenal", "了不起的"],
  ["rural", "鄉村的"],
  ["liquor", "烈酒"],
  ["site", "地點；場所"],
  ["code", "密碼；規範"],
  ["lean", "斜靠；瘦的"],
  ["pursue", "追求（動詞）"],
  ["pursuit", "追求（名詞）"],
  ["academic", "學術的"],
  ["academy", "學院"],
  ["maximum", "最大量"],
  ["maximize", "使增至最大"],
  ["minimum", "最小量"],
  ["minimize", "使降至最低"],
  ["manufacture", "製造；生產"],
  ["manufacturer", "製造商"],
  ["produce", "生產（動詞）"],
  ["cooperate", "合作（動詞）"],
  ["cooperation", "合作（名詞）"],
  ["cooperative", "合作的"],
  ["collaborate", "合作（共同研究）"],
  ["collaboration", "合作（名詞）"],
  ["overcome", "克服"],
  ["conquer", "征服"],
  ["defeat", "擊敗"],
  ["creation", "創造（名詞）"],
  ["create", "創造（動詞）"],
  ["creator", "創造者"],
  ["creature", "生物"],
  ["creative", "有創造力的"],
  ["creativity", "創造力"],
  ["recreation", "消遣；娛樂"],
  ["tragedy", "悲劇"],
  ["tragic", "悲劇的"],
  ["comedy", "喜劇"],
  ["comic", "喜劇的；漫畫"],
  ["comedian", "喜劇演員"],
  ["commerce", "商業"],
  ["commercial", "商業的"],
  ["constitute", "構成"],
  ["constitution", "憲法"],
  ["constitutional", "憲法的"],
  ["numerous", "極多的"],
  ["plentiful", "許多的"],
  ["abundant", "豐富的"],
  ["manual", "使用手冊；手工的"],
  ["quarrel", "爭吵"],
  ["squabble", "爭吵；口角"],
  ["argument", "爭執"],
  ["argue", "爭執；爭論"],
  ["renew", "更新（動詞）"],
  ["renewal", "更新（名詞）"],
  ["shade", "陰涼處；卷簾"],
  ["shady", "陰涼的"]
];

// ===== 句子填空資料：{ s:句子, blank:句子中該單字的形態, base:基準單字, zh:中文翻譯 } =====
// 填入句子形態（blank）或基準單字（base）皆算對
const SENTENCES = [
  { s: "Duncan likes the fast {blank} of life in the city.", blank: "pace", base: "pace", zh: "鄧肯喜歡城市快速的生活步調。" },
  { s: "Dad {blank} the floor as he waited for his daughter to give birth to his first grandchild.", blank: "paced", base: "pace", zh: "爸爸等候女兒生下他頭一個金孫時，一直來回踱步。" },
  { s: "The new student found it hard to gain the {blank} of others.", blank: "acceptance", base: "acceptance", zh: "新來的學生發現要被其他同學接納並不容易。" },
  { s: "You'd better {blank} copies of the documents for at least one year.", blank: "retain", base: "retain", zh: "這些文件你最好留著至少一年別丟。" },
  { s: "The boxer succeeded in {blank} his title as the heavyweight champion.", blank: "retaining", base: "retain", zh: "那位拳擊手成功地衛冕重量級冠軍。" },
  { s: "Alex was {blank} with his performance in the speech contest.", blank: "content", base: "content", zh: "亞歷克斯對他在演講比賽的表現很滿意。" },
  { s: "The manager {blank} the plan to set up a new factory in Mexico.", blank: "abandoned", base: "abandon", zh: "經理放棄在墨西哥建立新廠的計畫。" },
  { s: "The workers laid the {blank} before they built the walls.", blank: "foundation", base: "foundation", zh: "工人們打好地基，然後把牆砌起來。" },
  { s: "George has a solid {blank} in geography.", blank: "foundation", base: "foundation", zh: "喬治在地理學方面有很好的基礎。" },
  { s: "If you know how to {blank} the computer yourself, you can save lots of money.", blank: "assemble", base: "assemble", zh: "你若懂得組裝電腦，便可以省下很多錢。" },
  { s: "The boy can take the parts apart, but he can't {blank} them.", blank: "assemble", base: "assemble", zh: "這個小男孩懂得把零件分解，卻無法將它們組合起來。" },
  { s: "The elderly people {blank} in the hospital for free flu shots.", blank: "assembled", base: "assemble", zh: "老人們聚集在醫院裡打免費的流感疫苗。" },
  { s: "It's against the law to {blank} a criminal from the police.", blank: "shelter", base: "shelter", zh: "庇護罪犯躲避警方是違法的。" },
  { s: "The homeless man needed a {blank} from the cold rain.", blank: "shelter", base: "shelter", zh: "那個無家可歸的人需要一個躲避寒雨的庇護處。" },
  { s: "I had an unexpected {blank} with my old friend in the supermarket.", blank: "encounter", base: "encounter", zh: "我在超市和老友不期而遇。" },
  { s: "We went to a famous {blank} park during the summer vacation.", blank: "theme", base: "theme", zh: "暑假我們去了著名的主題公園。" },
  { s: "Violence is not a new {blank} in Taiwan.", blank: "phenomenon", base: "phenomenon", zh: "暴力在臺灣不是個新現象。" },
  { s: "Some people prefer {blank} areas for a quiet environment.", blank: "rural", base: "rural", zh: "有些人因為環境安靜而喜歡住鄉下。" },
  { s: "You have to be 18 to drink {blank} in Taiwan.", blank: "liquor", base: "liquor", zh: "在臺灣你必須年滿 18 歲才能喝酒。" },
  { s: "There were several people at the {blank} of the accident helping the survivors.", blank: "site", base: "site", zh: "意外現場有幾個人幫忙生還者。" },
  { s: "You have to obey the dress {blank} if you want to work here.", blank: "code", base: "code", zh: "如果你想在這裡工作，就必須遵守服裝規定。" },
  { s: "Each word on the list is {blank} to show the level of difficulty.", blank: "coded", base: "code", zh: "表上的所有字都加以編碼，以顯示其難度。" },
  { s: "The young man was {blank} against the wall, looking at the sky.", blank: "leaning", base: "lean", zh: "這年輕人斜靠著牆，仰望著天空。" },
  { s: "You should eat more vegetables and {blank} meat if you want to slim down.", blank: "lean", base: "lean", zh: "如果你想瘦下來就應該多吃青菜及瘦肉。" },
  { s: "With my father's support, I have been able to {blank} my dreams.", blank: "pursue", base: "pursue", zh: "有了我爸的支持，我才能夠去追尋我的夢想。" },
  { s: "Peter is planning to study abroad in {blank} of a bright future.", blank: "pursuit", base: "pursuit", zh: "彼得計畫要出國留學，以追求光明的前途。" },
  { s: "Laziness may be responsible for Timmy's bad {blank} performance.", blank: "academic", base: "academic", zh: "懶惰或許是提米學業成績不佳的原因。" },
  { s: "Give yourself a {blank} of 20 minutes to read the questions.", blank: "maximum", base: "maximum", zh: "給自己最多 20 分鐘的時間讀完題目。" },
  { s: "You must practice playing the piano for a {blank} of two hours every day.", blank: "minimum", base: "minimum", zh: "你每天必須練習彈鋼琴至少兩個小時。" },
  { s: "Our company {blank} electronic devices.", blank: "manufactures", base: "manufacture", zh: "我們公司生產電子儀器。" },
  { s: "The {blank} of newspapers requires a lot of wood pulp.", blank: "manufacture", base: "manufacture", zh: "製造報紙需要許多木漿。" },
  { s: "We {blank} with the police to locate the suspects.", blank: "cooperated", base: "cooperate", zh: "我們和警方合作找出嫌疑犯。" },
  { s: "I could not {blank} the difficulty of learning French, so I changed my major.", blank: "overcome", base: "overcome", zh: "我無法克服學法文的困難，因此我換了主修科系。" },
  { s: "This project will help foster the {blank} of new jobs.", blank: "creation", base: "creation", zh: "本計畫將有助於創造新的就業機會。" },
  { s: "The government plans to {blank} more jobs for young people.", blank: "create", base: "create", zh: "政府計畫為年輕人創造更多就業機會。" },
  { s: "Without {blank}, one can't be a successful artist.", blank: "creativity", base: "creativity", zh: "一個人若是缺乏創意，就沒辦法成為成功的藝術家。" },
  { s: "Jason's death was a {blank} to his family.", blank: "tragedy", base: "tragedy", zh: "傑森的死對他的家庭是一個慘劇。" },
  { s: "I prefer comedies to {blank}.", blank: "tragedies", base: "tragedy", zh: "我喜歡看喜劇勝於悲劇。" },
  { s: "The Taming of the Shrew is one of Shakespeare's most famous {blank}.", blank: "comedies", base: "comedy", zh: "《馴悍記》是莎士比亞最著名的喜劇之一。" },
  { s: "Taipei is Taiwan's center of {blank}.", blank: "commerce", base: "commerce", zh: "台北是臺灣的商業中心。" },
  { s: "According to the US {blank}, people have the right to speak freely.", blank: "Constitution", base: "constitution", zh: "根據美國憲法，人民享有言論自由權。" },
  { s: "Seven days {blank} a week.", blank: "constitute", base: "constitute", zh: "七天構成一個星期。" },
  { s: "She has made {blank} contributions to the project.", blank: "numerous", base: "numerous", zh: "她對這個專案做了許多貢獻。" },
  { s: "You should read the {blank} before you use the copier.", blank: "manual", base: "manual", zh: "在使用這部影印機之前，你應該先閱讀使用手冊。" },
  { s: "Mark doesn't like {blank} labor. He wants a desk job instead.", blank: "manual", base: "manual", zh: "馬克不喜歡勞力工作。他反而想要一份坐辦公室的工作。" },
  { s: "Terence is ill-tempered. He {blank} with his wife over almost everything.", blank: "quarrels", base: "quarrel", zh: "泰倫斯的脾氣不好。他幾乎每件事都會和太太爭吵。" },
  { s: "The boss decided to {blank} my contract for another year.", blank: "renew", base: "renew", zh: "老闆決定將與我續簽一年的合約。" },
  { s: "We took a rest in the {blank} of a large tree.", blank: "shade", base: "shade", zh: "我們在一棵大樹的樹蔭下休息。" },
  { s: "Monica's beauty and confidence put other contestants in the {blank}.", blank: "shade", base: "shade", zh: "莫妮卡的美貌和自信使其他參賽者相形失色。" }
];