// 高二開學考：高中科目（國文/數學/自然/社會/英文）題庫
// 依 南科實中 114 學年度高二開學考範圍表 + 教材版本對齊：
//   國文：龍騰版第一～二冊
//   數學：龍騰版第一～二冊（數A）
//   自然：物理(泰宇版力學一全冊)、化學(南一版物質與能量全冊)、生物(南一版細胞與遺傳全冊)、地科(南一版全冊)
//   社會：歷史(龍騰版第一二冊)、地理(南一版第一二冊)、公民(南一版)
// 每題可帶 topic 欄位標示章節主題，方便日後人工對齊課本章節
// 題型格式：
//   type: "single" | "multi" | "fill" | "calc"
//   q: 題幹
//   options: ["A","B","C","D"]          // single / multi 用
//   answer: 2 或 [1,3]                   // single: 正確選項索引；multi: 正確索引陣列
//   answerText: "正確解答文字"            // fill / calc 用
//   solution: "解題說明（答錯或看解析時顯示）"
//   passage: "閱讀文章（可選，顯示在題幹上方）"
//   image: "圖片網址（可選，顯示圖表/示意圖）"
//   topic: "單元主題標籤（顯示於解析，僅供整理）"
const SUBJECT_QUESTIONS = {
  "國文": [
    // ==== 龍騰第一冊 ====
    { type: "single", topic: "第一冊·散文", q: "龍騰版高一國文第一冊〈師說〉為唐代誰所作？", options: ["歐陽修", "蘇軾", "韓愈", "柳宗元"], answer: 2,
      solution: "〈師說〉為唐代韓愈所作，提倡從師求學的精神。" },
    { type: "single", topic: "第一冊·散文", q: "「弟子不必不如師，師不必賢於弟子」出自誰的哪一篇？", options: ["韓愈〈師說〉", "歐陽修〈醉翁亭記〉", "柳宗元〈三戒〉", "王安石〈遊褒禪山記〉"], answer: 0,
      solution: "此句出自韓愈〈師說〉，說明教學相長、師生相對的道理。" },
    { type: "single", topic: "第一冊·詩選", q: "陶淵明〈五柳先生傳〉中，五柳先生「好讀書，不求甚解」反映何種態度？", options: ["藏書成癖", "考據求證", "率性自適、重意會", "死記硬背"], answer: 2,
      solution: "「不求甚解」指不拘泥於字句，重領會精神，反映陶淵明灑脫自適的態度。" },
    { type: "single", topic: "第一冊·詩選", q: "〈桃花源記〉中「乃不知有漢，無論魏晉」凸顯桃花源居民什麼特點？", options: ["富甲一方", "博學多聞", "與世隔絕", "崇尚武力"], answer: 2,
      solution: "「不知有漢，無論魏晉」表示桃花源與外界長期隔絕，不知朝代更迭。" },
    { type: "single", topic: "第一冊·古文", q: "「箕踞而遨」中「箕踞」意為雙腿向前張開而坐，此坐姿透露出作者何種態度？", options: ["恭敬", "畏懼", "旁若無人、不拘禮法", "謙卑"], answer: 2,
      solution: "「箕踞」是不雅的坐姿，表現作者隨性、不受禮法拘束的態度。" },
    { type: "single", topic: "第一冊·古文", q: "蘇軾〈赤壁賦〉：「惟江上之清風，與山間之明月」強調什麼人生觀？", options: ["追逐名利", "及時行樂", "隨順自然、曠達自適", "悲觀厭世"], answer: 2,
      solution: "蘇軾以江上清風、山間明月比喻精神之富足，表現曠達的人生觀。" },
    { type: "single", topic: "第一冊·古文", q: "〈赤壁賦〉描寫的「赤壁」之戰，作者蘇軾是在何地被貶？", options: ["黃州", "儋州", "滁州", "潮州"], answer: 0,
      solution: "蘇軾因烏臺詩案被貶黃州，〈赤壁賦〉即作於黃州。" },
    { type: "single", topic: "第一冊·文言", q: "「舟行」之「行」在文言中常解作「去、往」，下列「行」字何者用法相同？", options: ["行將就木", "德之不修，學之不講", "三人行必有我師", "夜行遇鬼"], answer: 2,
      solution: "「三人行必有我師」之「行」為行走、前往；其餘多表「將要」或「行為」。" },
    { type: "single", topic: "第一冊·字音", q: "「噬」臍莫及的「噬」正確讀音是？", options: ["zhé", "sì", "yǎo", "shì"], answer: 3,
      solution: "「噬」讀 shì，意為咬。「噬臍莫及」比喻後悔不及。" },
    { type: "single", topic: "第一冊·字音", q: "「忸怩」的正確讀音是？", options: ["niù nì", "chǒu ní", "nǚ nì", "niǔ ní"], answer: 3,
      solution: "「忸怩」讀 niǔ ní，形容羞愧不自然。" },
    { type: "single", topic: "第一冊·字音", q: "「蹣跚」的正確讀音是？", options: ["bàn xiān", "pán shān", "pān shuān", "mán shān"], answer: 1,
      solution: "「蹣跚」讀 pán shān，形容步履不穩。" },
    { type: "single", topic: "第一冊·成語", q: "下列何者形容「事情已有眉目、即將完成」？", options: ["半途而廢", "垂手可得", "功虧一簣", "畫蛇添足"], answer: 2,
      solution: "「功虧一簣」指只差最後一簣土而未成，形容功敗垂成。" },
    { type: "single", topic: "第二冊·散文", q: "〈左忠毅公逸事〉的作者方苞屬清代哪一古文流派？", options: ["性靈派", "桐城派", "公安派", "竟陵派"], answer: 1,
      solution: "方苞為清代桐城派開創者，以「義法」論文。" },
    { type: "single", topic: "第二冊·散文", q: "歸有光〈項脊軒志〉以「庭有枇杷樹」收尾，主要寄託何種情感？", options: ["懷才不遇", "悼念亡妻", "思鄉", "感時傷逝"], answer: 1,
      solution: "「吾妻死之年所手植也」──以枇杷樹寄託對亡妻的思念。" },
    { type: "single", topic: "第二冊·詩選", q: "徐志摩〈再別康橋〉中「尋夢？撐一支長篙」的「康橋」指？", options: ["柏林大學", "牛津大學", "劍橋大學", "哈佛"], answer: 2,
      solution: "康橋即英國劍橋（Cambridge），徐志摩留學之地。" },
    { type: "single", topic: "第二冊·詩選", q: "余光中〈鄉愁〉運用哪種意象貫串全詩、象徵親情與故園？", options: ["江水", "郵票、船票、墳墓、海峽", "明月", "梅花"], answer: 1,
      solution: "〈鄉愁〉以郵票、船票、墳墓、海峽四個意象象徵層層愁緒。" },
    { type: "single", topic: "第二冊·詩選", q: "「新詩」又稱「白話詩」，下列何者不是新詩的特色？", options: ["用白話寫作", "常自由分行", "格律嚴格固定", "不講究平仄"], answer: 2,
      solution: "新詩打破舊詩格律，語言自由，不講究嚴格的平仄與字數。" },
    { type: "single", topic: "第二冊·古文", q: "〈超然臺記〉作者蘇軾，「超然」之名意在何種心境？", options: ["狂妄自大", "超脫得失、曠達自適", "消極悲觀", "厭世"], answer: 1,
      solution: "「超然」表現蘇軾超脫外在得失、自得其樂的人生態度。" },
    { type: "single", topic: "第二冊·文言", q: "「蓋將自其變者而觀之，則天地曾不能以一瞬！」出自？", options: ["劉禹錫〈陋室銘〉", "蘇軾〈赤壁賦〉", "范仲淹〈岳陽樓記〉", "陶淵明〈歸去來兮辭〉"], answer: 1,
      solution: "此句出自蘇軾〈赤壁賦〉，探討萬物變與不變之理。" },
    { type: "single", topic: "第二冊·字音", q: "「嵯峨」的正確讀音是？", options: ["cuó é", "cuò wǒ", "cuī é", "cí yá"], answer: 0,
      solution: "「嵯峨」讀 cuó é，形容山勢高峻。" },
    { type: "single", topic: "第二冊·字音", q: "「緋」聞的正確讀音是？", options: ["fēi", "fèn", "péi", "fěi"], answer: 0,
      solution: "「緋」讀 fēi，指紅色。「緋聞」即桃色新聞。" },
    { type: "single", topic: "第二冊·成語", q: "「風聲鶴唳，草木皆兵」形容什麼心理？", options: ["雄心壯志", "鎮定自若", "驚慌疑懼", "得意洋洋"], answer: 2,
      solution: "形容疑神疑鬼、驚恐不安，把風聲鶴唳都當成敵軍。" },
    { type: "single", topic: "應考常識", q: "國文考卷常出現的「修辭」中，「飛流直下三千尺」使用了何種修辭？", options: ["擬人", "對偶", "誇飾", "借代"], answer: 2,
      solution: "「三千尺」誇大瀑布之高，屬誇飾修辭。" },
    { type: "single", topic: "應考常識", q: "「春蠶到死絲方盡，蠟炬成灰淚始乾」中，「絲」諧音指何字？", options: ["詩", "私", "死", "思"], answer: 3,
      solution: "「絲」諧音「思」，借雙關表達思念之情。" },
    // ==== 多選 ====
    { type: "multi", topic: "第一冊·古文", q: "下列何者為先秦諸子百家？（多選）", options: ["道家", "儒家", "法家", "建安七子", "竹林七賢"], answer: [0, 1, 2],
      solution: "先秦諸子：儒、道、法、墨、名、陰陽等。建安七子與竹林七賢為後世文人集團。" },
    { type: "multi", topic: "第一冊·詩文", q: "下列何者被稱為「樂府雙璧」？（多選）", options: ["〈長恨歌〉", "〈木蘭詩〉", "〈孔雀東南飛〉", "〈琵琶行〉"], answer: [1, 2],
      solution: "「樂府雙璧」指北朝〈木蘭詩〉與東漢〈孔雀東南飛〉。" },
    { type: "multi", topic: "第二冊·詩選", q: "下列何者為現代詩人？（多選）", options: ["李白", "余光中", "杜甫", "鄭愁予"], answer: [1, 3],
      solution: "余光中、鄭愁予為現代詩人；李白、杜甫為唐代詩人。" },
    { type: "multi", topic: "第二冊·古文", q: "下列何者為唐宋八大家之一？（多選）", options: ["李商隱", "柳宗元", "韓愈", "歐陽修", "杜甫"], answer: [1, 2, 3],
      solution: "唐宋八大家：韓愈、柳宗元、歐陽修、曾鞏、王安石、蘇洵、蘇軾、蘇轍。杜甫、李商隱為詩人。" },
    // ==== 填空 ====
    { type: "single", topic: "第一冊·詩文", q: "陶淵明〈飲酒〉：「採菊東籬下，＿＿＿＿。」", options: ["欲辯已忘言", "悠然見南山", "心遠地自偏", "飛鳥相與還"], answer: 1,
      solution: "原句：「採菊東籬下，悠然見南山。」表現隱逸自得之情。" },
    { type: "single", topic: "第一冊·詩文", q: "王維〈鹿柴〉：「空山不見人，但聞＿＿＿＿。」", options: ["鳥鳴聲", "鐘磬音", "犬吠聲", "人語響"], answer: 3,
      solution: "原句：「空山不見人，但聞人語響。」以聲襯靜。" },
    { type: "single", topic: "第二冊·詩文", q: "李商隱〈無題〉：「春蠶到死絲方盡，＿＿＿＿。」", options: ["東風無力百花殘", "蠟炬成灰淚始乾", "青鳥殷勤為探看", "夜吟應覺月光寒"], answer: 1,
      solution: "原句描寫至死不渝的相思之情。" },
    { type: "single", topic: "第二冊·詩文", q: "蘇軾〈水調歌頭〉：「但願人長久，＿＿＿＿。」", options: ["千里共嬋娟", "月有陰晴圓缺", "轉朱閣低綺戶", "無風水面琉璃滑"], answer: 0,
      solution: "寄託對天下人團圓美好的祝願。" },
    { type: "single", topic: "第一冊·詩歌", q: "《詩經》是我國第一部詩歌總集，其「六義」中不含下列何者？", options: ["風", "雅", "頌", "賦、比、興之外再加「序」"], answer: 3,
      solution: "《詩經》六義為風、雅、頌（體裁）與賦、比、興（作法）。" },
    { type: "single", topic: "第一冊·詩歌", q: "「關關雎鳩，在河之洲」出自《詩經》何篇？", options: ["〈鹿鳴〉", "〈蒹葭〉", "〈關雎〉", "〈木瓜〉"], answer: 2,
      solution: "〈關雎〉為《詩經》首篇。" },
    { type: "single", topic: "第一冊·散文", q: "〈愛蓮說〉作者周敦頤為宋代何家學派代表人物？", options: ["考據", "桐城", "心學", "理學（道學）"], answer: 3,
      solution: "周敦頤為北宋理學家，〈愛蓮說〉借物喻人。" },
    { type: "single", topic: "第一冊·散文", q: "「出淤泥而不染，濯清漣而不妖」出自？", options: ["陶淵明〈五柳先生傳〉", "周敦頤〈愛蓮說〉", "劉禹錫〈陋室銘〉", "柳宗元〈小石潭記〉"], answer: 1,
      solution: "名句出自周敦頤〈愛蓮說〉，象徵君子高潔。" },
    { type: "single", topic: "第一冊·散文", q: "〈小石潭記〉的作者柳宗元，因何事被貶永州？", options: ["戊戌政變", "永貞革新失敗", "烏臺詩案", "安史之亂"], answer: 1,
      solution: "柳宗元因王叔文「永貞革新」失敗被貶永州。" },
    { type: "single", topic: "第一冊·古文", q: "「世有伯樂，然後有千里馬」出自韓愈哪一篇？", options: ["〈師說〉", "〈馬說〉", "〈進學解〉", "〈原道〉"], answer: 1,
      solution: "此為韓愈〈馬說〉名句，借千里馬喻人才須遇識者。" },
    { type: "single", topic: "第二冊·散文", q: "〈岳陽樓記〉作者范仲淹，名句「先天下之憂而憂」所寄託的胸懷是？", options: ["歸隱山林", "縱情享樂", "明哲保身", "以天下為己任"], answer: 3,
      solution: "抒發以天下為己任、憂樂與民同在的胸懷。" },
    { type: "single", topic: "第二冊·散文", q: "〈醉翁亭記〉「醉翁之意不在酒，在乎山水之間也」的作者是？", options: ["王安石", "蘇軾", "司馬光", "歐陽修"], answer: 3,
      solution: "〈醉翁亭記〉為歐陽修貶滁州所作。" },
    { type: "single", topic: "第二冊·詩歌", q: "李商隱〈登樂遊原〉：「夕陽無限好，只是近黃昏。」主要藉夕陽抒發何種情感？", options: ["思鄉", "壯志凌雲", "讚美自然", "感傷遲暮"], answer: 3,
      solution: "以夕陽的美好而短暫，感傷美好事物難久存。" },
    { type: "single", topic: "第二冊·詩歌", q: "杜甫被尊為？", options: ["詩聖", "詩佛", "詩鬼", "詩仙"], answer: 0,
      solution: "杜甫為「詩聖」，李白為「詩仙」，王維為「詩佛」。", },
    { type: "single", topic: "第二冊·詩歌", q: "「會當凌絕頂，一覽眾山小」描寫的是哪座山？", options: ["泰山", "華山", "黃山", "衡山"], answer: 0,
      solution: "杜甫〈望嶽〉寫泰山，抒發壯志。" },
    { type: "single", topic: "第二冊·古文", q: "「先帝創業未半而中道崩殂」出自哪一篇？", options: ["孟子〈梁惠王下〉", "司馬遷〈報任安書〉", "魏徵〈諫太宗十思疏〉", "諸葛亮〈出師表〉"], answer: 3,
      solution: "此為〈出師表〉開篇。" },
    { type: "single", topic: "第二冊·古文", q: "〈諫太宗十思疏〉的作者是？", options: ["褚遂良", "魏徵", "房玄齡", "李靖"], answer: 1,
      solution: "〈諫太宗十思疏〉為魏徵所作。" },
    { type: "single", topic: "第二冊·文言", q: "「之」字在「送孟浩然之廣陵」中作何解釋？", options: ["助詞無義", "到、往", "代詞", "的"], answer: 1,
      solution: "「之」在此為動詞「到、前往」。" },
    { type: "single", topic: "第二冊·字音", q: "「惴」惴不安的「惴」讀音是？", options: ["zhuì", "duān", "chuǎn", "zhuó"], answer: 0,
      solution: "「惴惴」讀 zhuì，形容憂懼不安。" },
    { type: "single", topic: "第二冊·字音", q: "「愜」意的正確讀音是？", options: ["jiā", "qiè", "xié", "qià"], answer: 1,
      solution: "「愜意」讀 qiè，指稱心如意。" },
    { type: "single", topic: "第二冊·成語", q: "「不刊之論」的「刊」意為？", options: ["刊登", "訂正", "刪改", "印刷"], answer: 1,
      solution: "「刊」原義為刪改，「不刊之論」指不可更改的至理名言。" },
    { type: "single", topic: "第二冊·成語", q: "「琳瑯滿目」多用以形容？", options: ["雜亂無章", "家徒四壁", "眼花撩亂", "美好的事物繁多"], answer: 3,
      solution: "「琳瑯滿目」指眼前美好的事物很多。" },
    { type: "single", topic: "第二冊·閱讀",
      passage: "閱讀：「予獨愛蓮之出淤泥而不染，濯清漣而不妖，中通外直，不蔓不枝，香遠益清。」",
      q: "此段以蓮喻人，主要在讚美君子哪種品格？", options: ["隱逸避世", "富貴顯達", "圓融處世", "高潔正直、不隨波逐流"], answer: 3,
      solution: "「出淤泥而不染」喻君子潔身自好、正直不阿。" },
    // ==== 多選補充 ====
    { type: "multi", topic: "第一冊·作者", q: "下列何者為「田園詩人」？（多選）", options: ["王維", "李白", "柳宗元", "陶淵明"], answer: [0, 3],
      solution: "陶淵明開田園詩之先，王維亦善田園山水詩。" },
    { type: "multi", topic: "第二冊·修辭", q: "下列何者運用了「對偶」修辭？（多選）", options: ["飛流直下三千尺", "明月松間照，清泉石上流", "兩個黃鸝鳴翠柳，一行白鷺上青天", "春蠶到死絲方盡"], answer: [1, 2],
      solution: "「明月松間照，清泉石上流」與「兩個黃鸝……一行白鷺……」為工整對偶；其餘分別用雙關與誇飾。" },
    { type: "multi", topic: "第二冊·文言", q: "下列「者」字何者為「……的人」之代詞用法？（多選）", options: ["仁者樂山", "知之者不如好之者", "逝者如斯夫", "有朋自遠方來"], answer: [0, 1, 2],
      solution: "「知之者」（了解的人）、「仁者」（仁德之人）、「逝者」（流去的時光）皆指特定者；「有朋」無「者」字作「的」義。" },
    { type: "multi", topic: "第二冊·文體", q: "下列何者為「駢文」（講求對仗）？（多選）", options: ["師說", "赤壁賦", "與朱元思書", "滕王閣序"], answer: [2, 3],
      solution: "〈滕王閣序〉、〈與朱元思書〉為駢文；〈師說〉、〈赤壁賦〉為散體古文。" },
    { type: "single", topic: "第一冊·詩歌", q: "王之渙〈登鸛雀樓〉：「欲窮千里目，＿＿＿＿。」", options: ["將進酒杯莫停", "白日依山盡", "更上一層樓", "黃河入海流"], answer: 2,
      solution: "名句勉人欲見遠方須再加努力。" },
    { type: "single", topic: "第一冊·詩歌", q: "李白〈靜夜思〉：「舉頭望明月，＿＿＿＿。」", options: ["對影成三人", "低頭思故鄉", "月是故鄉明", "疑是地上霜"], answer: 1,
      solution: "抒發對故鄉的思念。" },
    { type: "single", topic: "第二冊·詩歌", q: "白居易〈賦得古原草送別〉：「野火燒不盡，＿＿＿＿。」", options: ["春風吹又生", "遠芳侵古道", "萋萋滿別情", "晴翠接荒城"], answer: 0,
      solution: "「野火燒不盡，春風吹又生。」" },
    { type: "single", topic: "第二冊·詩歌", q: "杜甫〈春望〉：「國破山河在，＿＿＿＿。」", options: ["感時花濺淚", "恨別鳥驚心", "城春草木深", "烽火連三月"], answer: 2,
      solution: "寫安史之亂後長安殘破的景象。" },
    { type: "single", topic: "第一冊·散文", q: "柳宗元〈小石潭記〉：「潭中魚可百許頭，＿＿＿＿。」", options: ["俶爾遠逝", "皆若空遊無所依", "往來翕忽", "似與遊者相樂"], answer: 1,
      solution: "石潭清澈透亮，魚似在空中遊動。" },
    { type: "single", topic: "第二冊·散文", q: "范仲淹〈岳陽樓記〉：「不以物喜，＿＿＿＿。」", options: ["處江湖之遠", "先天下之憂而憂", "不以己悲", "後天下之樂而樂"], answer: 2,
      solution: "不因外物或自身得失而喜悲。" },
    { type: "single", topic: "第二冊·閱讀",
      passage: "閱讀：「世間行樂亦如此，古來萬事東流水。別君去兮何時還？」",
      q: "此詩句「古來萬事東流水」意含何種思想？", options: ["頌揚功名", "萬事如流水般消逝、無常", "重視河流", "萬事順利"], answer: 1,
      solution: "以「東流水」喻萬事流逝，帶有世事無常的慨嘆。" },
    { type: "single", topic: "應考·國字注音", q: "「盪漾」的正確讀音是？", options: ["dàng yàng", "tàng yàng", "dāng yáng", "dàng yán"], answer: 0,
      solution: "「盪漾」讀 dàng yàng，形容水波起伏。" },
    { type: "single", topic: "應考·國字注音", q: "「澎湃」的正確讀音是？", options: ["píng pài", "péng pò", "péng pài", "pēng bài"], answer: 2,
      solution: "「澎湃」讀 péng pài，形容水勢或情緒激盪。" },
    { type: "single", topic: "應考·字形", q: "下列何者字形正確？", options: ["前途盲盲", "前途芒芒", "前徒茫茫", "前途茫茫"], answer: 3,
      solution: "「前途茫茫」為正確寫法。" }
  ],
  "數學": [
    // ==== 第一冊：數與式、指數、對數、多項式 ====
    { type: "single", topic: "第一冊·數與式", q: "設 A={1,2,3}，B={2,3,4}，則 A∪B 的元素個數為？", options: ["2", "4", "3", "6"], answer: 1,
      solution: "A∪B={1,2,3,4}，共 4 個元素。" },
    { type: "single", topic: "第一冊·數與式", q: "|x−3|<2 的解為？", options: ["x<1 或 x>5", "1<x<5", "1≤x≤5", "−1<x<5"], answer: 1,
      solution: "|x−3|<2 ⇒ −2<x−3<2 ⇒ 1<x<5。" },
    { type: "single", topic: "第一冊·數與式", q: "√18 可化簡為？", options: ["6√3", "9√2", "2√3", "3√2"], answer: 3,
      solution: "√18=√(9×2)=3√2。" },
    { type: "single", topic: "第一冊·指數", q: "2³ × 2⁴ = ？", options: ["8⁷", "4⁷", "2¹²", "2⁷"], answer: 3,
      solution: "同底相乘指數相加：2³⁺⁴=2⁷。" },
    { type: "single", topic: "第一冊·指數", q: "10⁻² 的值為？", options: ["0.1", "0.02", "0.01", "100"], answer: 2,
      solution: "10⁻²=1/10²=0.01。" },
    { type: "single", topic: "第一冊·對數", q: "log₁₀ 1000 = ？", options: ["100", "4", "2", "3"], answer: 3,
      solution: "因 10³=1000，故 log₁₀1000=3。" },
    { type: "single", topic: "第一冊·對數", q: "log₂ 32 = ？", options: ["16", "6", "5", "4"], answer: 2,
      solution: "因 2⁵=32，故 log₂32=5。" },
    { type: "single", topic: "第一冊·對數", q: "若 log₃ x=2，則 x=？", options: ["8", "3²=9", "9", "6"], answer: 2,
      solution: "log₃x=2 ⇒ x=3²=9。" },
    { type: "single", topic: "第一冊·多項式", q: "多項式 f(x)=x²−5x+6 的因式分解為？", options: ["(x−2)(x+3)", "(x+2)(x−3)", "(x+2)(x+3)", "(x−2)(x−3)"], answer: 3,
      solution: "x²−5x+6=(x−2)(x−3)。" },
    { type: "single", topic: "第一冊·多項式", q: "若 f(x)=x²，則 f(x+1)−f(x)=？", options: ["2x+1", "x+1", "2x−1", "1"], answer: 0,
      solution: "(x+1)²−x²=x²+2x+1−x²=2x+1。" },
    { type: "single", topic: "第一冊·多項式", q: "二次函數 y=x²−4x+3 的對稱軸為 x=？", options: ["3", "−2", "1", "2"], answer: 3,
      solution: "配方法 y=(x−2)²−1，對稱軸 x=2。" },
    { type: "single", topic: "第一冊·多項式", q: "x²+6x+9 可化簡為？", options: ["(x+3)²", "(x+6)²", "(x−3)²", "(x+9)²"], answer: 0,
      solution: "完全平方：x²+6x+9=(x+3)²。" },
    { type: "single", topic: "第一冊·多項式", q: "多項式除法中，(x³−8)÷(x−2) 的商式為？", options: ["x²+4", "x²+2x+4", "x²−2x+4", "x²−4"], answer: 1,
      solution: "x³−8=(x−2)(x²+2x+4)，商式為 x²+2x+4。" },
    { type: "single", topic: "第一冊·直線與圓", q: "直線 y=2x+1 的斜率為？", options: ["3", "1", "2", "−2"], answer: 2,
      solution: "y=mx+b，斜率 m=2。" },
    { type: "single", topic: "第一冊·直線與圓", q: "點 (−2,3) 位於第幾象限？", options: ["第三", "第二", "第一", "第四"], answer: 1,
      solution: "x<0、y>0 為第二象限。" },
    { type: "single", topic: "第一冊·直線與圓", q: "圓心在 (1,2)、半徑 3 的圓方程式為？", options: ["(x−1)²+(y−2)²=9", "(x−1)²+(y−2)²=3", "(x+1)²+(y+2)²=3", "(x+1)²+(y+2)²=9"], answer: 0,
      solution: "圓方程式 (x−h)²+(y−k)²=r² ⇒ (x−1)²+(y−2)²=9。" },
    // ==== 第二冊：數列、數據分析、排列組合、機率、三角比 ====
    { type: "single", topic: "第二冊·數列", q: "等差數列 3, 7, 11, 15, … 的公差為？", options: ["4", "3", "5", "7"], answer: 0,
      solution: "公差 = 後項−前項 = 7−3=4。" },
    { type: "single", topic: "第二冊·數列", q: "等差數列首項 2、公差 3，第 5 項為？", options: ["15", "14", "17", "20"], answer: 1,
      solution: "a₅=a₁+4d=2+4×3=14。" },
    { type: "single", topic: "第二冊·數列", q: "等比數列 2, 6, 18, … 的公比為？", options: ["3", "2", "4", "6"], answer: 0,
      solution: "公比 = 6÷2=3。" },
    { type: "single", topic: "第二冊·數據分析", q: "資料 3, 5, 7, 9, 11 的平均數為？", options: ["6", "8", "7", "5"], answer: 2,
      solution: "(3+5+7+9+11)÷5=35÷5=7。" },
    { type: "single", topic: "第二冊·數據分析", q: "資料 2, 4, 6, 8, 10 的中位數（奇數個）為？", options: ["4", "7", "5", "6"], answer: 3,
      solution: "排序後中間項為 6。" },
    { type: "single", topic: "第二冊·排列組合", q: "5!（5 的階乘）= ？", options: ["60", "25", "20", "120"], answer: 3,
      solution: "5!=5×4×3×2×1=120。" },
    { type: "single", topic: "第二冊·排列組合", q: "C(5,2)（從 5 取 2）的值為？", options: ["10", "15", "5", "20"], answer: 0,
      solution: "C(5,2)=5×4/2!=10。" },
    { type: "single", topic: "第二冊·機率", q: "擲一顆公正骰子一次，出現偶數的機率為？", options: ["1/6", "1/2", "2/3", "1/3"], answer: 1,
      solution: "偶數有 2、4、6 三種，機率=3/6=1/2。" },
    { type: "single", topic: "第二冊·三角比", q: "sin 90° 的值為？", options: ["√3/2", "0", "1/2", "1"], answer: 3,
      solution: "sin90°=1。" },
    { type: "single", topic: "第二冊·三角比", q: "tan 45° 的值為？", options: ["√2", "1/2", "1", "0"], answer: 2,
      solution: "tan45°=sin45°/cos45°=1。" },
    { type: "single", topic: "第二冊·三角比", q: "cos 0° 的值為？", options: ["0", "1", "√3/2", "1/2"], answer: 1,
      solution: "cos0°=1。" },
    // ==== 多選 ====
    { type: "multi", topic: "第一冊·數與式", q: "下列哪些為有理數？（多選）", options: ["√2", "−4", "0.5", "1/3", "π"], answer: [1, 2, 3],
      solution: "有理數可表為分數：1/3、0.5、−4。√2、π為無理數。" },
    { type: "multi", topic: "第一冊·多項式", q: "下列哪些函數為偶函數（f(−x)=f(x)）？（多選）", options: ["y=x²", "y=|x|", "y=cos x", "y=x³"], answer: [0, 1, 2],
      solution: "x²、|x|、cos x 皆為偶函數；x³ 為奇函數。" },
    { type: "multi", topic: "第二冊·排列組合", q: "從 A、B、C、D 四人中選 2 人出席，下列敘述何者正確？（多選）", options: ["排列 P(4,2)=12", "組合 C(4,2)=6", "有 12 種選法", "有 6 種選法"], answer: [0, 1, 3],
      solution: "組合 C(4,2)=6；若論順序則排列 P(4,2)=12。" },
    { type: "multi", topic: "第二冊·機率", q: "從一疊 52 張撲克牌抽 1 張，下列何者正確？（多選）", options: ["抽到紅心的機率為 1/4", "抽到黑桃的機率為 1/4", "抽到 A 的機率為 1/13", "抽到紅心 A 的機率為 1/13"], answer: [0, 1, 2],
      solution: "黑桃 13 張：13/52=1/4；A 有 4 張：4/52=1/13；紅心 A 僅 1 張：1/52。" },
    // ==== 填空 ====
    { type: "fill", topic: "第一冊·數與式", q: "計算 √16 = ？", answerText: "4",
      solution: "4²=16，故 √16=4。" },
    { type: "fill", topic: "第一冊·指數", q: "2⁵ = ？", answerText: "32",
      solution: "2⁵=2×2×2×2×2=32。" },
    { type: "fill", topic: "第一冊·對數", q: "log₁₀ 1 = ？", answerText: "0",
      solution: "因 10⁰=1，故 log₁₀1=0。" },
    { type: "fill", topic: "第二冊·三角形", q: "直角三角形中，直角所對的邊稱為什麼？", answerText: "斜邊",
      solution: "直角三角形最長邊為斜邊。" },
    { type: "calc", topic: "第一冊·多項式", q: "展開 (x+2)(x−3)。", answerText: "x²−x−6",
      solution: "(x+2)(x−3)=x²−3x+2x−6=x²−x−6。" },
    { type: "calc", topic: "第一冊·多項式", q: "化簡 (2x+1)²。", answerText: "4x²+4x+1",
      solution: "(2x+1)²=(2x)²+2·2x·1+1²=4x²+4x+1。" },
    { type: "calc", topic: "第二冊·數列", q: "等差數列首項 3、公差 5，求第 6 項。", answerText: "28",
      solution: "a₆=a₁+5d=3+5×5=28。" },
    { type: "calc", topic: "第二冊·數據分析", q: "計算資料 1, 3, 5, 7, 9 的平均數。", answerText: "5",
      solution: "(1+3+5+7+9)÷5=25÷5=5。" },
    // ==== 數學補充 ====
    { type: "single", topic: "第一冊·數與式", q: "有理數與無理數統稱為什麼？", options: ["自然數", "複數", "實數", "整數"], answer: 2,
      solution: "實數＝有理數＋無理數。" },
    { type: "single", topic: "第一冊·數與式", q: "循環小數 0.3̅（0.333…）屬於？", options: ["無理數", "有理數", "整數", "虛數"], answer: 1,
      solution: "循環小數可表成分數，為有理數。" },
    { type: "single", topic: "第一冊·數與式", q: "3/4 的小數表示為？", options: ["0.75", "0.74", "0.34", "0.3"], answer: 0,
      solution: "3÷4=0.75。" },
    { type: "single", topic: "第一冊·指數", q: "(2³)² = ？", options: ["2⁹", "4⁵", "2⁶", "2⁵"], answer: 2,
      solution: "指數相乘：(2³)²=2⁶。" },
    { type: "single", topic: "第一冊·指數", q: "5⁰ = ？", options: ["0", "10", "5", "1"], answer: 3,
      solution: "任何非零數的零次方為 1。" },
    { type: "single", topic: "第一冊·對數", q: "log₂ 1 = ？", options: ["1", "0", "1/2", "2"], answer: 1,
      solution: "因 2⁰=1，故 log₂1=0。" },
    { type: "single", topic: "第一冊·對數", q: "若 log x=2（底為 10），則 x=？", options: ["100", "20", "10⁰", "102"], answer: 0,
      solution: "log₁₀x=2 ⇒ x=10²=100。" },
    { type: "single", topic: "第一冊·多項式", q: "多項式 (x+1)(x−1) = ？", options: ["x²−2", "x²+1", "x²−1", "x²−x−1"], answer: 2,
      solution: "平方差：(x+1)(x−1)=x²−1。" },
    { type: "single", topic: "第一冊·多項式", q: "若 f(x)=3x−2，則 f(2) = ？", options: ["7", "6", "4", "3"], answer: 2,
      solution: "f(2)=3×2−2=4。" },
    { type: "single", topic: "第一冊·多項式", q: "二次函數 y=−x²+4 的最大值為？", options: ["16", "0", "4", "−4"], answer: 2,
      solution: "開口向下，頂點 (0,4) 即最大值 4。" },
    { type: "single", topic: "第一冊·直線與圓", q: "兩點 (0,0) 與 (3,4) 的距離為？", options: ["25", "12", "5", "7"], answer: 2,
      solution: "√(3²+4²)=√25=5。" },
    { type: "single", topic: "第一冊·直線與圓", q: "直線過 (0,0) 與 (1,2)，其斜率為？", options: ["2", "1/2", "−2", "0"], answer: 0,
      solution: "斜率=(2−0)/(1−0)=2。" },
    { type: "single", topic: "第一冊·直線與圓", q: "點 (3,4) 到原點（半徑 5）是否在圓 x²+y²=25 上？", options: ["圓內", "是", "圓外", "否"], answer: 1,
      solution: "3²+4²=25，故在圓上。" },
    { type: "single", topic: "第二冊·數列", q: "等比數列 1, 2, 4, … 的第 4 項為？", options: ["16", "6", "8", "32"], answer: 2,
      solution: "公比 2：a₄=1×2³=8。" },
    { type: "single", topic: "第二冊·數列", q: "等差數列 5, 8, 11, … 公差為？", options: ["3", "5", "13", "8"], answer: 0,
      solution: "8−5=3。" },
    { type: "single", topic: "第二冊·數據分析", q: "資料 2, 5, 8, 11, 14 的平均數為？", options: ["9", "7", "10", "8"], answer: 3,
      solution: "(2+5+8+11+14)÷5=40÷5=8。" },
    { type: "single", topic: "第二冊·數據分析", q: "資料的標準差衡量的是？", options: ["最大值", "資料個數", "資料的離散程度", "平均數"], answer: 2,
      solution: "標準差衡量資料離散（分散）程度。" },
    { type: "single", topic: "第二冊·排列組合", q: "0,1,2 三個數字排列成三位數（不重複）有幾種？", options: ["3", "4", "9", "6"], answer: 1,
      solution: "百位不能為 0：2×2×1=4 種。" },
    { type: "single", topic: "第二冊·排列組合", q: "C(4,0) = ？", options: ["4", "1", "0", "24"], answer: 1,
      solution: "C(4,0)=1（不取任何元素）。" },
    { type: "single", topic: "第二冊·機率", q: "擲兩顆公正骰子，點數和為 7 的機率為？", options: ["1/6", "1/12", "1/8", "1/36"], answer: 0,
      solution: "和為 7 有 6 種：6/36=1/6。" },
    { type: "single", topic: "第二冊·機率", q: "摸彩袋有 3 紅 2 白，任取 1 顆為紅球的機率為？", options: ["2/5", "3/2", "1/5", "3/5"], answer: 3,
      solution: "3÷(3+2)=3/5。" },
    { type: "single", topic: "第二冊·三角比", q: "sin 60° 的值為？", options: ["√2/2", "√3/2", "1/2", "1"], answer: 1,
      solution: "sin60°=√3/2。" },
    { type: "single", topic: "第二冊·三角比", q: "直角三角形中，對邊 3、斜邊 5，則 sin 該角 = ？", options: ["5/3", "3/4", "4/5", "3/5"], answer: 3,
      solution: "sin=對邊/斜邊=3/5。" },
    { type: "calc", topic: "第一冊·數與式", q: "解方程式 2x+3=11。", answerText: "x=4",
      solution: "2x=11−3=8，x=4。" },
    { type: "calc", topic: "第一冊·多項式", q: "化簡 3(x−1)+2x。", answerText: "5x−3",
      solution: "3x−3+2x=5x−3。" },
    { type: "calc", topic: "第一冊·直線與圓", q: "求過點 (0,0) 與 (3,4) 的直線斜率。", answerText: "4/3",
      solution: "m=(4−0)/(3−0)=4/3。" },
    { type: "calc", topic: "第二冊·數列", q: "等比數列首項 3、公比 2，求第 3 項。", answerText: "12",
      solution: "a₃=a₁·r²=3×2²=12。" },
    { type: "calc", topic: "第二冊·機率", q: "從 5 件正品與 3 件次品中任取 1 件，取到次品的機率為？（以分數）", answerText: "3/8",
      solution: "3÷(5+3)=3/8。" },
    { type: "fill", topic: "第一冊·數與式", q: "(−3)² = ？", answerText: "9",
      solution: "負數平方為正數：(−3)²=9。" },
    { type: "fill", topic: "第一冊·指數", q: "3³ = ？", answerText: "27",
      solution: "3×3×3=27。" },
    { type: "fill", topic: "第二冊·三角比", q: "直角三角形中，直角所對的邊稱為什麼？", answerText: "斜邊",
      solution: "直角三角形最長邊為斜邊。" }
  ],
  "自然": [
    // ==== 物理：泰宇版力學一全冊 ====
    { type: "single", topic: "物理·運動學", q: "國際單位制中，速度的單位是？", options: ["m", "N", "m/s", "m/s²"], answer: 2,
      solution: "速度=位移÷時間，單位 m/s。" },
    { type: "single", topic: "物理·運動學", q: "自由落體時，忽略空氣阻力，物體做哪種運動？", options: ["等加速度", "圓周", "簡諧", "等速度"], answer: 0,
      solution: "自由落體受重力 g 影響，做等加速度運動。" },
    { type: "single", topic: "物理·動力學", q: "牛頓第一運動定律又稱為什麼定律？", options: ["作用反作用", "能量守恆", "慣性定律", "萬有引力"], answer: 2,
      solution: "第一運動定律描述慣性現象，稱慣性定律。" },
    { type: "single", topic: "物理·動力學", q: "F=ma 中，若 m=2kg、a=3 m/s²，則 F=？", options: ["5 N", "6 N", "1 N", "2/3 N"], answer: 1,
      solution: "F=ma=2×3=6 N。" },
    { type: "single", topic: "物理·功與能量", q: "功的公式 W=？", options: ["F/s", "F×s", "F+t", "m×a"], answer: 1,
      solution: "功 = 力 × 沿力方向位移 = F×s。" },
    { type: "single", topic: "物理·功與能量", q: "功率的定義為？", options: ["功×時間", "力×速度", "能量×距離", "功÷時間"], answer: 3,
      solution: "功率 = 作功 ÷ 時間 = W/t，單位瓦特 W。" },
    { type: "single", topic: "物理·動量", q: "動量的定義為（質量 m、速度 v）？", options: ["m×v²", "m×a", "m×v", "F×t"], answer: 2,
      solution: "動量 p=mv，單位 kg·m/s。" },
    { type: "single", topic: "物理·圓周與萬有引力", q: "行星繞太陽做近似圓周運動，所需向心力來源為？", options: ["摩擦力", "張力", "電磁力", "萬有引力"], answer: 3,
      solution: "太陽對行星的萬有引力提供向心力。" },
    { type: "single", topic: "物理·運動學", q: "一台車以均速 20 m/s 行駛 10 秒，共行進多少公尺？", options: ["30", "2000", "2", "200"], answer: 3,
      solution: "距離=速度×時間=20×10=200 m。" },
    // ==== 化學：南一版物質與能量全冊 ====
    { type: "single", topic: "化學·物質的組成", q: "原子由哪三種基本粒子組成？", options: ["質子、中子、電子", "中子、電子、夸克", "質子、中子、原子核", "質子、電子、光子"], answer: 0,
      solution: "原子由質子、中子（構成原子核）與電子所組成。" },
    { type: "single", topic: "化學·物質的組成", q: "水的化學式是？", options: ["O₂", "H₂O", "CO₂", "NaCl"], answer: 1,
      solution: "水由兩氫一氧組成，化學式 H₂O。" },
    { type: "single", topic: "化學·溶液", q: "食鹽（氯化鈉）的化學式為？", options: ["NaOH", "CaCO₃", "NaCl", "KCl"], answer: 2,
      solution: "食鹽為氯化鈉 NaCl。" },
    { type: "single", topic: "化學·溶液", q: "pH=7 時的溶液呈何性？", options: ["強酸", "中性", "鹼性", "酸性"], answer: 1,
      solution: "pH=7 為中性；<7 酸性，>7 鹼性。" },
    { type: "single", topic: "化學·常見反應", q: "石蕊試紙遇鹼變什麼顏色？", options: ["紅色", "藍色", "無色", "紫色"], answer: 1,
      solution: "石蕊遇鹼變藍、遇酸變紅。" },
    { type: "single", topic: "化學·物質的組成", q: "氧分子的化學式為？", options: ["CO₂", "O", "O₂", "O₃"], answer: 2,
      solution: "氧氣為雙原子分子 O₂。" },
    { type: "single", topic: "化學·生活化學", q: "下列何種氣體是造成溫室效應的主要氣體之一？", options: ["CO₂", "O₂", "N₂", "Ar"], answer: 0,
      solution: "CO₂ 是主要的溫室氣體。" },
    { type: "single", topic: "化學·常見反應", q: "酸與鹼作用生成鹽與水的反應稱為？", options: ["燃燒", "氧化還原", "中和反應", "分解"], answer: 2,
      solution: "酸的 H⁺ 與鹼的 OH⁻ 結合成水，生成鹽，稱中和反應。" },
    // ==== 生物：南一版細胞與遺傳全冊 ====
    { type: "single", topic: "生物·細胞的構造", q: "植物細胞中，進行光合作用的胞器是？", options: ["粒線體", "核糖體", "液泡", "葉綠體"], answer: 3,
      solution: "葉綠體含葉綠素，進行光合作用。" },
    { type: "single", topic: "生物·細胞的構造", q: "細胞進行有氧呼吸的主要胞器是？", options: ["粒線體", "葉綠體", "溶體", "中心粒"], answer: 0,
      solution: "粒線體進行有氧呼吸產生 ATP。" },
    { type: "single", topic: "生物·細胞的構造", q: "植物細胞有而動物細胞沒有的構造是？", options: ["核糖體", "細胞核", "粒線體", "細胞壁"], answer: 3,
      solution: "植物細胞特有細胞壁（與葉綠體、大液泡）。" },
    { type: "single", topic: "生物·遺傳", q: "DNA 主要存在於細胞的何處？", options: ["細胞膜", "細胞核", "液泡", "細胞壁"], answer: 1,
      solution: "真核生物 DNA 位於細胞核的染色體中。" },
    { type: "single", topic: "生物·遺傳", q: "孟德爾遺傳定律中，顯性與隱性基因以哪一符號表示？", options: ["大寫表顯性、小寫表隱性", "中文", "數字", "希臘字母"], answer: 0,
      solution: "遺傳學以大寫字母表顯性（如 A）、小寫表隱性（如 a）。" },
    { type: "single", topic: "生物·細胞的構造", q: "人體面積最大的器官是？", options: ["皮膚", "肝臟", "肺", "小腸"], answer: 0,
      solution: "皮膚為人體最大器官。" },
    { type: "single", topic: "生物·代謝", q: "血液中負責攜帶氧氣的是？", options: ["血漿", "紅血球（血紅素）", "血小板", "白血球"], answer: 1,
      solution: "紅血球內血紅素可與氧結合。" },
    // ==== 地科：南一版全冊 ====
    { type: "single", topic: "地科·地球", q: "地球大氣中含量最高的氣體是？", options: ["氮氣 N₂", "二氧化碳 CO₂", "氧氣 O₂", "氬 Ar"], answer: 0,
      solution: "大氣約 78% 為氮氣。" },
    { type: "single", topic: "地科·地球", q: "台灣地震頻繁的主因是位於哪兩個板塊交界？", options: ["美洲與太平洋", "南極與阿拉伯", "非洲與印度", "歐亞與菲律賓海板塊"], answer: 3,
      solution: "台灣位於歐亞板塊與菲律賓海板塊交界。" },
    { type: "single", topic: "地科·地球", q: "地球自轉方向為？", options: ["自南向北", "自東向西", "自西向東", "靜止"], answer: 2,
      solution: "地球自西向東自轉。" },
    { type: "single", topic: "地科·天文", q: "地球繞行的中心天體是？", options: ["北極星", "月球", "火星", "太陽"], answer: 3,
      solution: "地球為太陽系行星，繞太陽公轉。" },
    { type: "single", topic: "地科·天文", q: "1 天文單位（AU）約等於？", options: ["地球到太陽的平均距離", "地球到月球距離", "太陽到比鄰星距離", "地球半徑"], answer: 0,
      solution: "1 AU = 地球與太陽平均距離約 1.5 億公里。" },
    { type: "single", topic: "地科·地球", q: "岩石的主要三大類不包括下列何者？", options: ["變質岩", "火成岩", "化石岩", "沉積岩"], answer: 2,
      solution: "三大岩類為火成岩、沉積岩、變質岩；化石岩非岩類分類。" },
    // ==== 多選 ====
    { type: "multi", topic: "物理·運動", q: "下列哪些為向量（有大小與方向）？（多選）", options: ["加速度", "位移", "速度", "速度值標量"], answer: [0, 1, 2],
      solution: "速度、位移、加速度皆為向量；純量如速率、質量。" },
    { type: "multi", topic: "自然·再生能源", q: "下列何者屬於可再生能源？（多選）", options: ["煤炭", "太陽能", "風能", "石油"], answer: [1, 2],
      solution: "太陽能、風能為再生能源；煤炭、石油為化石燃料。" },
    { type: "multi", topic: "生物·遺傳", q: "DNA 的組成包含下列哪些？（多選）", options: ["腺嘌呤 A", "尿嘧啶 U", "鳥嘌呤 G", "胸腺嘧啶 T"], answer: [0, 2, 3],
      solution: "DNA 四種含氮鹼基為 A、T、G、C；U 僅存在 RNA。" },
    { type: "multi", topic: "地科·地球", q: "下列哪些現象常發生於板塊交界處？（多選）", options: ["火山活動", "地震", "平原廣布", "海溝"], answer: [0, 1, 3],
      solution: "板塊交界地殼活動劇烈，多地震、火山、海溝。" },
    // ==== 計算／填空改選擇 ====
    { type: "single", topic: "物理·運動學", q: "一物以 100 公尺跑 20 秒，平均速度為多少 m/s？", options: ["5", "20", "500", "0.2"], answer: 0,
      solution: "v=100÷20=5 m/s。" },
    { type: "single", topic: "物理·功與能量", q: "地表重力加速度 g 約為多少 m/s²？", options: ["9.8", "11", "8.9", "10"], answer: 0,
      solution: "g≈9.8 m/s²。" },
    { type: "single", topic: "化學·溶液", q: "一大氣壓下純水的沸點為攝氏多少度？", options: ["90", "120", "80", "100"], answer: 3,
      solution: "1 atm 下純水沸點 100°C。" },
    { type: "single", topic: "生物·遺傳", q: "人體細胞的性染色體，男性為何？", options: ["XX", "XY", "XO", "YY"], answer: 1,
      solution: "男性性染色體為 XY。" },
    { type: "single", topic: "物理·功與能量", q: "將 500 公克水從 20°C 加熱到 100°C，水比熱 1 cal/(g·°C)，吸熱多少 cal？", options: ["4000", "40000", "5000", "40000×20"], answer: 1,
      solution: "Q=mcΔT=500×1×(100−20)=40000 cal。" },
    { type: "single", topic: "化學·溶液", q: "質量 200 公克、體積 40 cm³ 的物質，密度為多少 g/cm³？", options: ["0.2", "5", "8", "40"], answer: 1,
      solution: "密度=200÷40=5 g/cm³。" },
    { type: "single", topic: "物理·運動學", q: "自由落下 2 秒後（g=10 m/s²）的速度為多少 m/s（初速 0）？", options: ["2", "5", "20", "10"], answer: 2,
      solution: "v=gt=10×2=20 m/s。" },
    { type: "single", topic: "物理·動量", q: "質量 2 kg 物體以 3 m/s 運動，動量為多少 kg·m/s？", options: ["5", "1.5", "12", "6"], answer: 3,
      solution: "p=mv=2×3=6 kg·m/s。" },
    // ==== 自然補充 ====
    { type: "single", topic: "物理·運動學", q: "加速度的國際單位是？", options: ["N", "m/s²", "m", "m/s"], answer: 1,
      solution: "加速度=速度變化÷時間，單位 m/s²。" },
    { type: "single", topic: "物理·運動學", q: "物體從靜止開始自由落下 2 秒（g=10），位移為多少公尺？", options: ["10", "40", "20", "5"], answer: 2,
      solution: "s=½gt²=½×10×4=20 m。" },
    { type: "single", topic: "物理·動力學", q: "牛頓第三運動定律又稱？", options: ["萬有引力", "能量守恆", "作用力與反作用力", "慣性"], answer: 2,
      solution: "第三定律：作用力與反作用力大小相等、方向相反。" },
    { type: "single", topic: "物理·功與能量", q: "動能 Ek 的公式為？", options: ["½mv²", "F×s", "mv", "mgh"], answer: 0,
      solution: "動能 Ek=½mv²。" },
    { type: "single", topic: "物理·功與能量", q: "重力位能的公式為？", options: ["mgh", "m×a", "½mv²", "mv"], answer: 0,
      solution: "重力位能 U=mgh。" },
    { type: "single", topic: "物理·動量", q: "不受外力時，系統總動量保持不變，此稱為何？", options: ["質量守恆", "動量守恆", "能量守恆", "電荷守恆"], answer: 1,
      solution: "孤立系統總動量守恆。" },
    { type: "single", topic: "化學·物質的組成", q: "原子的原子核主要由哪兩種粒子構成？", options: ["電子與光子", "質子與電子", "中子與電子", "質子與中子"], answer: 3,
      solution: "原子核含質子與中子，電子繞核外運行。" },
    { type: "single", topic: "化學·常見反應", q: "鐵在空氣中與氧作用生鏽，此屬何種反應？", options: ["分解", "氧化", "還原", "中和"], answer: 1,
      solution: "鐵氧化生鏽屬氧化反應。" },
    { type: "single", topic: "化學·溶液", q: "一杯糖水，超過溶解量未溶的糖沉在杯底，此溶液狀態為？", options: ["未飽和", "飽和", "蒸發", "過飽和"], answer: 1,
      solution: "已無法再溶解更多溶質，稱飽和溶液。" },
    { type: "single", topic: "生物·細胞的構造", q: "細胞中負責合成蛋白質的胞器是？", options: ["核糖體", "葉綠體", "粒線體", "液泡"], answer: 0,
      solution: "核糖體為蛋白質合成場所。" },
    { type: "single", topic: "生物·細胞的構造", q: "細胞膜的主要功能不包括下列何者？", options: ["進行光合作用", "訊息傳遞", "控制物質進出", "保護細胞"], answer: 0,
      solution: "光合作用在葉綠體進行；細胞膜主要控制物質進出。" },
    { type: "single", topic: "生物·遺傳", q: "DNA 的雙股螺旋結構由誰提出模型？", options: ["孟德爾", "達爾文", "華生與克里克", "孟克"], answer: 2,
      solution: "1953 年華生與克里克提出 DNA 雙螺旋模型。" },
    { type: "single", topic: "地科·大氣", q: "大氣中哪一層可阻擋大部分紫外線？", options: ["平流層上部", "臭氧層", "電離層", "對流層"], answer: 1,
      solution: "臭氧層吸收大量紫外線保護地球生物。" },
    { type: "single", topic: "地科·海洋", q: "影響台灣沿岸的『黑潮』為哪種洋流？", options: ["風流", "潮汐流", "暖流", "寒流"], answer: 2,
      solution: "黑潮為暖流，沿台灣東岸北上。" },
    { type: "single", topic: "地科·天文", q: "地球自轉一周所需的時間約為？", options: ["12 小時", "30 天", "365 天", "24 小時"], answer: 3,
      solution: "地球自轉一周約 24 小時（一日）。" },
    { type: "single", topic: "地科·天文", q: "地球以何軸自轉，導致四季更替隨公轉而變化？", options: ["南北極點固定", "地軸傾斜 23.5°", "黃道面平行", "赤道面"], answer: 1,
      solution: "地軸傾斜 23.5°，使陽光直射點南北移動造成四季。" },
    { type: "multi", topic: "物理·功與能量", q: "下列何者為「能量」的形式？（多選）", options: ["長度", "熱能", "位能", "動能"], answer: [1, 2, 3],
      solution: "動能、位能、熱能皆為能量形式；長度為物理量非能量。" },
    { type: "multi", topic: "化學·物質的組成", q: "下列何者為「化合物」？", options: ["食鹽 NaCl", "氧氣 O₂", "水 H₂O", "二氧化碳 CO₂"], answer: [0, 2, 3],
      solution: "化合物由不同元素組成：水、二氧化碳、食鹽；O₂ 為元素非化合物。" },
    { type: "multi", topic: "生物·細胞", q: "下列哪些構造存在於植物細胞？（多選）", options: ["中心粒", "大液泡", "細胞壁", "葉綠體"], answer: [1, 2, 3],
      solution: "植物細胞特有細胞壁、葉綠體、大液泡；中心粒多見於動物細胞。" },
    { type: "multi", topic: "地科·地球", q: "地球科學研究範疇包含下列哪些？（多選）", options: ["文學", "海洋", "地質", "大氣"], answer: [1, 2, 3],
      solution: "地球科學涵蓋大氣、海洋、地質、天文等；文學屬人文。" },
    { type: "single", topic: "物理·運動學", q: "一物以 50 公尺跑 10 秒，平均速度為多少 m/s？", options: ["50", "10", "5", "0.5"], answer: 2,
      solution: "v=50÷10=5 m/s。" },
    { type: "single", topic: "化學·溶液", q: "一大氣壓下純水的凝固點為攝氏多少度？", options: ["10", "0", "-5", "100"], answer: 1,
      solution: "1 atm 下純水凝固點（冰點）為 0°C。" },
    { type: "single", topic: "物理·功與能量", q: "質量 2 kg 物體速度 4 m/s，動能為多少焦耳？", options: ["8", "32", "4", "16"], answer: 3,
      solution: "Ek=½mv²=½×2×16=16 J。" },
    { type: "single", topic: "生物·遺傳", q: "一對夫婦皆為異型合子 Aa，生一孩子為 aa（隱性純合）的機率為多少？", options: ["1/4", "1/3", "3/4", "1/2"], answer: 0,
      solution: "Aa×Aa → AA:Aa:aa=1:2:1，aa 機率 1/4。" },
    { type: "single", topic: "地科·距離", q: "光速 3×10⁸ m/s，光走 1 秒的距離為多少公里？", options: ["3×10⁸", "300000", "30000", "3000"], answer: 1,
      solution: "3×10⁸ m=3×10⁵ km=300000 km。" }
  ],
  "社會": [
    // ==== 歷史：龍騰版第一、二冊 ====
    { type: "single", topic: "歷史·台灣史", q: "台灣在那一年由清廷簽訂條約割讓給日本？", options: ["1945", "1895", "1860", "1912"], answer: 1,
      solution: "1895 年簽訂〈馬關條約〉，台灣割讓日本。" },
    { type: "single", topic: "歷史·台灣史", q: "鄭成功驅逐荷蘭人、建立明鄭政權是在？", options: ["1662 年", "1895 年", "1624 年", "1683 年"], answer: 0,
      solution: "1662 年鄭成功驅逐荷蘭東印度公司。" },
    { type: "single", topic: "歷史·台灣史", q: "荷蘭人據台灣南部約在何時？", options: ["1895–1945", "1662–1683", "1624–1662", "1600–1620"], answer: 2,
      solution: "荷蘭東印度公司約 1624 年入據，1662 年被鄭氏驅逐。" },
    { type: "single", topic: "歷史·台灣史", q: "台灣在二戰結束後由日本回歸中華民國，是在？", options: ["1949 年", "1943 年", "1945 年", "1947 年"], answer: 2,
      solution: "1945 年二戰結束，台灣光復。" },
    { type: "single", topic: "歷史·中國史", q: "中華民國於何年成立？", options: ["1912 年", "1911 年", "1949 年", "1921 年"], answer: 0,
      solution: "辛亥革命後，中華民國於 1912 年元旦成立。" },
    { type: "single", topic: "歷史·中國史", q: "第一次世界大戰後，中國因何事件掀起五四運動？", options: ["西安事變", "甲午戰爭", "九一八事變", "巴黎和會山東問題"], answer: 3,
      solution: "1919 年巴黎和會決定將山東權益移交日本，引爆五四運動。" },
    { type: "single", topic: "歷史·世界史", q: "文藝復興最早興起於哪一地區？", options: ["義大利", "英國", "法國", "德國"], answer: 0,
      solution: "文藝復興起源於義大利的城市如佛羅倫斯。" },
    { type: "single", topic: "歷史·世界史", q: "1789 年法國大革命因何社會矛盾而起？", options: ["氣候變遷", "階級不平等（三級會議）", "人口過剩", "宗教戰爭"], answer: 1,
      solution: "法國三級會議中第三等級受壓迫，引發大革命。" },
    { type: "single", topic: "歷史·台灣史", q: "清代台灣「一府二鹿三艋舺」中的「府」指？", options: ["台南府城", "基隆", "高雄", "台北"], answer: 0,
      solution: "清代台灣最重要的城市為台南府城。" },
    { type: "single", topic: "歷史·中國史", q: "下列何者是導致唐朝滅亡後中國再度分裂的主因？", options: ["科舉制度", "絲路暢通", "佛教盛行", "藩鎮割據"], answer: 3,
      solution: "唐末藩鎮割據，導致五代十國分裂。" },
    // ==== 地理：南一版第一、二冊 ====
    { type: "single", topic: "地理·台灣地形", q: "台灣本島最高峰是？", options: ["玉山", "雪山", "阿里山", "南湖大山"], answer: 0,
      solution: "玉山 3952 公尺，為台灣第一高峰。" },
    { type: "single", topic: "地理·台灣地形", q: "台灣最長的河川是？", options: ["淡水河", "高屏溪", "濁水溪", "曾文溪"], answer: 2,
      solution: "濁水溪約 186 公里，為台灣最長河川。" },
    { type: "single", topic: "地理·台灣地形", q: "台灣面積最大的平原是？", options: ["蘭陽平原", "屏東平原", "嘉南平原", "台東縱谷"], answer: 2,
      solution: "嘉南平原為台灣最大平原。" },
    { type: "single", topic: "地理·台灣地形", q: "北回歸線通過台灣的哪兩個縣市？", options: ["台中、台南", "嘉義、花蓮", "屏東、台東", "台北、高雄"], answer: 1,
      solution: "北回歸線橫越嘉義與花蓮。" },
    { type: "single", topic: "地理·台灣地形", q: "台灣沿海的『黑潮』是哪一種洋流？", options: ["鹽度流", "風流", "暖流", "寒流"], answer: 2,
      solution: "黑潮為溫暖的太平洋洋流，影響台灣氣候。" },
    { type: "single", topic: "地理·地形", q: "台灣東部的縱谷位於哪兩列山脈之間？", options: ["阿里山與太平山", "中央山脈與海岸山脈", "中央與玉山", "玉山與雪山"], answer: 1,
      solution: "台東縱谷介於中央山脈與海岸山脈之間。" },
    { type: "single", topic: "地理·台灣", q: "台灣最大的天然湖泊是？", options: ["澄清湖", "琵琶湖", "日月潭", "鯉魚潭"], answer: 2,
      solution: "日月潭為台灣最大天然湖泊。" },
    { type: "single", topic: "地理·世界", q: "世界上面積最大的國家為？", options: ["中國", "加拿大", "美國", "俄羅斯"], answer: 3,
      solution: "俄羅斯面積最大。" },
    // ==== 公民：南一版 ====
    { type: "single", topic: "公民·憲法", q: "中華民國憲法何年開始施行？", options: ["1912 年", "1945 年", "1949 年", "1947 年"], answer: 3,
      solution: "憲法於 1947 年 12 月 25 日施行。" },
    { type: "single", topic: "公民·憲法", q: "我國「五院」中，負責法律審議與立法者為？", options: ["考試院", "司法院", "立法院", "行政院"], answer: 2,
      solution: "立法院為最高立法機關。" },
    { type: "single", topic: "公民·人權", q: "憲法第二章規定的人民權利，主要保障何者？", options: ["選舉義務", "納稅義務", "基本人權", "服役義務"], answer: 2,
      solution: "憲法第二章「人民之權利義務」保障言論、宗教、平等等基本權。" },
    { type: "single", topic: "公民·政府", q: "我國總統由何種方式產生？", options: ["國會間接選舉", "人民直接選舉", "軍方指派", "世襲"], answer: 1,
      solution: "總統由全體選舉人直接選舉產生。" },
    { type: "single", topic: "公民·政府", q: "下列何者不屬於「五院」？", options: ["司法部", "監察院", "立法院", "行政院"], answer: 0,
      solution: "五院為行政、立法、司法、考試、監察；「司法部」非五院。" },
    { type: "single", topic: "公民·人權", q: "下列何者屬於憲法保障之基本權？", options: ["言論自由", "隨意拘留他人", "立法免責", "納稅免費"], answer: 0,
      solution: "言論自由為憲法保障之基本權。" },
    // ==== 多選 ====
    { type: "multi", topic: "歷史·世界史", q: "下列哪些事件與「法國大革命」相關？（多選）", options: ["人權宣言", "工業革命", "三級會議", "巴士底獄攻陷"], answer: [0, 2, 3],
      solution: "巴士底獄、人權宣言、三級會議皆與法國大革命有關。" },
    { type: "multi", topic: "地理·台灣", q: "台灣的氣候主要受哪些因素影響？（多選）", options: ["季風", "地形抬升", "極地寒流", "黑潮暖流"], answer: [0, 1, 3],
      solution: "台灣受季風、黑潮暖流與高山地形影響。" },
    { type: "multi", topic: "公民·政府", q: "下列何者屬於我國「五院」？（多選）", options: ["監察院", "考試院", "司法院", "行政院", "立法院"], answer: [0, 1, 2, 3, 4],
      solution: "五院為行政、立法、司法、考試、監察，五院皆屬。" },
    { type: "multi", topic: "歷史·台灣史", q: "下列何者為台灣史上的「移民」？（多選）", options: ["閩南移民", "1949 年隨政府來台者", "西班牙人首次登台", "客家移民"], answer: [0, 1, 3],
      solution: "閩南、客家及 1949 年遷台者皆為移民；西班牙登台屬殖民探險非移民。" },
    // ==== 填空／計算改選擇 ====
    { type: "single", topic: "地理·台灣", q: "台灣的總面積約為多少萬平方公里？", options: ["36", "3.6", "0.36", "360"], answer: 1,
      solution: "台灣約 3.6 萬平方公里。" },
    { type: "single", topic: "地理·台灣", q: "北回歸線緯度約為北緯多少度？", options: ["66.5", "33.5", "13.5", "23.5"], answer: 3,
      solution: "北回歸線約北緯 23.5°。" },
    { type: "single", topic: "歷史·台灣史", q: "台灣在第二次世界大戰後於哪一年光復？", options: ["1895", "1921", "1945", "1949"], answer: 2,
      solution: "1945 年二戰結束，台灣回歸中華民國。" },
    { type: "single", topic: "公民·人權", q: "中華民國憲法第二章的主題是？", options: ["司法", "基本國策", "人民之權利義務", "選舉"], answer: 2,
      solution: "憲法第二章為「人民之權利義務」。" },
    { type: "single", topic: "地理·人口", q: "某縣人口 230 萬人、面積 2300 平方公里，人口密度為多少（人/km²）？", options: ["1000", "100", "10000", "2300"], answer: 0,
      solution: "密度=2,300,000÷2300=1000 人/km²。" },
    { type: "single", topic: "地理·距離", q: "以時速 60 公里行駛 2 小時，共行駛多少公里？", options: ["1200", "30", "120", "62"], answer: 2,
      solution: "距離=60×2=120 km。" },
    // ==== 社會補充 ====
    { type: "single", topic: "歷史·台灣史", q: "清朝時期台灣設『一府三縣』，其中的『府』指哪一府？", options: ["高雄府", "台南府", "台北府", "台灣府"], answer: 3,
      solution: "清代台灣設台灣府，隸屬福建省。" },
    { type: "single", topic: "歷史·台灣史", q: "移民渡台開墾時常見的『唐山過台灣』『唐山』指？", options: ["京都", "中國大陸", "唐山縣", "廣州"], answer: 1,
      solution: "台灣移民稱祖籍地（中國大陸）為唐山。" },
    { type: "single", topic: "歷史·台灣史", q: "台灣第一個有鐵路的朝代／時期是？", options: ["清治時期（劉銘傳）", "日治初期", "荷治時期", "鄭氏時期"], answer: 0,
      solution: "清治劉銘傳推動台灣首段鐵路。" },
    { type: "single", topic: "歷史·中國史", q: "秦始皇統一六國後實行的文字統一稱？", options: ["行書", "楷書", "小篆", "草書"], answer: 2,
      solution: "秦朝統一文字為小篆（後多通行隸書）。" },
    { type: "single", topic: "歷史·中國史", q: "『楚漢相爭』最終由誰建立漢朝？", options: ["蕭何", "劉邦", "項羽", "韓信"], answer: 1,
      solution: "劉邦擊敗項羽，建立西漢。" },
    { type: "single", topic: "歷史·中國史", q: "三國鼎立中，魏國由誰建立？", options: ["曹操", "曹操之子曹丕", "孫權", "劉備"], answer: 1,
      solution: "曹丕篡漢建立魏；劉備建蜀漢、孫權建東吳。" },
    { type: "single", topic: "歷史·世界史", q: "開闢新航路、發現美洲大陸的航海家是？", options: ["達伽馬", "鄭和", "麥哲倫", "哥倫布"], answer: 3,
      solution: "1492 年哥倫布橫渡大西洋到達美洲。" },
    { type: "single", topic: "歷史·世界史", q: "工業革命最早始於哪一國家？", options: ["法國", "英國", "美國", "日本"], answer: 1,
      solution: "18 世紀工業革命始於英國。" },
    { type: "single", topic: "歷史·世界史", q: "第一次世界大戰爆發的時間是？", options: ["1914 年", "1900 年", "1918 年", "1939 年"], answer: 0,
      solution: "一次大戰於 1914 年爆發。" },
    { type: "single", topic: "地理·地形", q: "下列何者為『侵蝕地形』？", options: ["V 形谷", "三角洲", "沖積扇", "氾濫平原"], answer: 0,
      solution: "V 形谷為河流侵蝕下切所成；其餘多為堆積地形。" },
    { type: "single", topic: "地理·地形", q: "『冰河』在台灣何種山區曾有遺跡？", options: ["海岸線", "平原", "高山（如玉山、雪山）", "盆地"], answer: 2,
      solution: "台灣高山曾受冰河侵蝕，留有圈谷等遺跡。" },
    { type: "single", topic: "地理·氣候", q: "台灣冬季主要受哪一風影響較乾冷？", options: ["焚風", "西南季風", "東北季風", "颱風"], answer: 2,
      solution: "冬季東北季風使台灣北部較涼冷、迎風面多雨。" },
    { type: "single", topic: "地理·氣候", q: "『梅雨』主要發生在台灣的哪個季節？", options: ["秋季", "冬季", "春末夏初（五六月）", "盛夏"], answer: 2,
      solution: "台灣梅雨季約為五、六月，屬滯留鋒面降雨。" },
    { type: "single", topic: "地理·人口", q: "台灣人口分布的最主要特徵是？", options: ["南部多、北部少", "均勻分布", "山地多、平原少", "西部多、東部少"], answer: 3,
      solution: "台灣人口集中西部平原，東部山地較少。" },
    { type: "single", topic: "地理·世界", q: "下列哪一洲面積最大？", options: ["亞洲", "美洲", "歐洲", "非洲"], answer: 0,
      solution: "亞洲為世界上最大洲。" },
    { type: "single", topic: "公民·人權", q: "「人身自由」主要由憲法哪一條保障？", options: ["第十條", "第一百條", "第一條", "第八條"], answer: 3,
      solution: "憲法第八條保障人民身體（人身）自由。" },
    { type: "single", topic: "公民·人權", q: "「法律之前人人平等」稱為？", options: ["參政權", "受教育權", "生存權", "平等權"], answer: 3,
      solution: "法律之前人人平等為平等權之體現。" },
    { type: "single", topic: "公民·政府", q: "行政院院長由誰任命？", options: ["司法院", "總統", "立法院", "人民選舉"], answer: 1,
      solution: "行政院長由總統提名、立法院同意後任命。" },
    { type: "single", topic: "公民·政府", q: "監督行政部門、行使彈劾與審計權的是哪一院？", options: ["司法院", "考試院", "監察院", "立法院"], answer: 2,
      solution: "監察院行使彈劾、糾舉、審計之權。" },
    { type: "single", topic: "公民·經濟", q: "下列何種制度主要由「供需法則」調節價格？", options: ["自然經濟", "軍用經濟", "計畫經濟", "市場經濟"], answer: 3,
      solution: "市場經濟由供需決定價格。" },
    { type: "single", topic: "公民·社會", q: "「家庭、學校、媒體」等對個人行為影響的過程稱？", options: ["社會分工", "社會化", "升學", "公民投票"], answer: 1,
      solution: "社會化指個人學習社會規範、內化價值的過程。" },
    { type: "multi", topic: "歷史·台灣史", q: "下列哪些為台灣史上的「原住民族」？（多選）", options: ["阿美族", "泰雅族", "排灣族", "滿族"], answer: [0, 1, 2],
      solution: "阿美、排灣、泰雅為台灣原住民族；滿族為中國東北民族。" },
    { type: "multi", topic: "地理·台灣", q: "台灣的主要山脈包含下列哪些？（多選）", options: ["阿爾卑斯山", "海岸山脈", "雪山山脈", "中央山脈"], answer: [1, 2, 3],
      solution: "台灣有中央、雪山、玉山、阿里山、海岸山脈；阿爾卑斯山在歐洲。" },
    { type: "multi", topic: "公民·人權", q: "下列何者屬於「基本人權」？（多選）", options: ["集會結社", "言論自由", "任意搜查他人", "信仰自由"], answer: [0, 1, 3],
      solution: "言論、信仰、集會結社皆是基本權；任意搜查他人違反基本權。" },
    { type: "multi", topic: "公民·政府", q: "關於我國政府組織，下列何者正確？（多選）", options: ["採五權分立", "立法院掌立法", "總統為國家元首", "地方自治"], answer: [0, 1, 2, 3],
      solution: "我國採五權分立、總統為元首、立法院掌立法並實行地方自治。" },
    { type: "multi", topic: "歷史·世界史", q: "下列哪些與「文藝復興」相關？（多選）", options: ["達文西", "工業革命", "人文主義", "佛羅倫斯"], answer: [0, 2, 3],
      solution: "文藝復興以人文主義為精神、義大利佛羅倫斯為中心、達文西為代表性藝術家；工業革命非屬之。" },
    { type: "multi", topic: "地理·地形", q: "下列哪些為「堆積地形」？（多選）", options: ["氾濫平原", "沖積扇", "三角洲", "V 形谷"], answer: [0, 1, 2],
      solution: "三角洲、沖積扇、氾濫平原為堆積地形；V 形谷為侵蝕地形。" },
    { type: "single", topic: "歷史·世界史", q: "文藝復興最早起源於哪一國家？", options: ["英國", "德國", "法國", "義大利"], answer: 3,
      solution: "文藝復興起源於義大利。" },
    { type: "single", topic: "地理·台灣", q: "台灣本島最高峰的玉山海拔約多少公尺？", options: ["3952", "1000", "2997", "3886"], answer: 0,
      solution: "玉山 3952 公尺，為台灣第一高峰。" },
    { type: "single", topic: "公民·人權", q: "中華民國憲法第二章的主題為？", options: ["人民之權利義務", "地方制度", "立法", "行政"], answer: 0,
      solution: "憲法第二章為「人民之權利義務」。" }
  ],
  "英文": [
    // ==== 龍騰版高中英文第一、二冊：字彙、文法、句構、閱讀 ====
    { type: "single", topic: "英文·字彙", q: "下列何者意為「（動）達成、實現」？", options: ["attack", "achieve", "avoid", "arrive"], answer: 1,
      solution: "achieve 達成、實現；arrive 到達；avoid 避免；attack 攻擊。" },
    { type: "single", topic: "英文·字彙", q: "「environment」的中文意思為？", options: ["經驗", "學生", "設備", "環境"], answer: 3,
      solution: "environment 環境。" },
    { type: "single", topic: "英文·字彙", q: "下列何者意為「（形）方便的」？", options: ["continuous", "comfortable", "convenient", "content"], answer: 2,
      solution: "convenient 方便的；comfortable 舒適的。" },
    { type: "single", topic: "英文·字彙", q: "「describe」的名詞形式為？", options: ["description", "desire", "dictation", "describer"], answer: 0,
      solution: "describe（動）→ description（名）描述。" },
    { type: "single", topic: "英文·字彙", q: "「suggest」的過去式拼法是？", options: ["sugested", "suggestting", "suggested", "suggestd"], answer: 2,
      solution: "suggest 為規則動詞，過去式加 -ed：suggested。" },
    { type: "single", topic: "英文·字彙", q: "下列何者與「famous」意思最接近？", options: ["foreign", "well-known", "familiar", "unknown"], answer: 1,
      solution: "famous 有名的 ≈ well-known 眾所周知。", },
    { type: "single", topic: "英文·字彙", q: "「habit」的常用片語「get into the habit of + Ving」意為？", options: ["擁有壞習慣", "戒除壞習慣", "養成……的習慣", "欣賞習慣"], answer: 2,
      solution: "get into the habit of + Ving 養成……的習慣。" },
    { type: "single", topic: "英文·文法", q: "下列何者正確？She ______ to school every day.", options: ["gone", "going", "goes", "go"], answer: 2,
      solution: "第三人稱單數現在式加 -es：go → goes。" },
    { type: "single", topic: "英文·文法", q: "「There ______ many books on the shelf.」空格應填？", options: ["be", "being", "are", "is"], answer: 2,
      solution: "many books 為複數，用 There are。" },
    { type: "single", topic: "英文·文法", q: "「I have ______ finished my homework.」（完成式時間副詞）", options: ["tomorrow", "ago", "already", "yesterday"], answer: 2,
      solution: "already 已，常用於現在完成式。" },
    { type: "single", topic: "英文·文法", q: "「If it ______ tomorrow, we will stay home.」空格應填？", options: ["is raining", "rained", "will rain", "rains"], answer: 3,
      solution: "If 引導條件句表未來要用現在式：rains。" },
    { type: "single", topic: "英文·文法", q: "下列何者是「被動語態」的正確形式？The cake ______ by Mom.", options: ["made", "be made", "is make", "was made"], answer: 3,
      solution: "被動語態 be + p.p.，過去式 was made。" },
    { type: "single", topic: "英文·文法", q: "「He is good at ______ English.」空格應填？", options: ["speaking", "to speak", "speak", "spoke"], answer: 0,
      solution: "be good at + Ving，用 speaking。" },
    { type: "single", topic: "英文·文法", q: "「She has been to Japan twice.」此句時態為？", options: ["現在完成式", "未來式", "過去完成式", "過去式"], answer: 0,
      solution: "has/have + p.p. 為現在完成式，表迄至現在的經驗。" },
    { type: "single", topic: "英文·字彙", q: "「Although it was raining, the game continued.」此句的連接詞 Although 意為？", options: ["雖然", "因為", "所以", "直到"], answer: 0,
      solution: "although 雖、雖然，表讓步。" },
    { type: "single", topic: "英文·字彙", q: "「opportunity」意為？", options: ["意見", "操作", "機會", "反對"], answer: 2,
      solution: "opportunity 機會。" },
    { type: "single", topic: "英文·字彙", q: "下列何者意為「（形）相當的、相似的」？", options: ["simple", "symbol", "seldom", "similar"], answer: 3,
      solution: "similar 相似的；seldom 很少（副）。" },
    { type: "single", topic: "英文·字彙", q: "「depend on」意為？", options: ["延遲", "拒絕", "放棄", "依賴、取決於"], answer: 3,
      solution: "depend on 依賴、取決於。" },
    { type: "single", topic: "英文·字彙", q: "「reduce」的反義詞是？", options: ["decrease", "remind", "refuse", "increase"], answer: 3,
      solution: "reduce 減少 ↔ increase 增加。" },
    { type: "single", topic: "英文·字彙", q: "「arrange」的名詞為？", options: ["arrange", "arrival", "arrangement", "arriving"], answer: 2,
      solution: "arrange（動）安排 → arrangement（名）。" },
    { type: "single", topic: "英文·文法", q: "「Neither of the answers ______ correct.」空格應填？", options: ["were", "is", "be", "are"], answer: 1,
      solution: "Neither of + 複數名詞 視為單數，動詞用 is。" },
    { type: "single", topic: "英文·文法", q: "「He is taller than ______ in his class.」空格應填？", options: ["someone", "everyone else", "anyone", "anyone else"], answer: 3,
      solution: "比較級加 than anyone else 表全班最高。" },
    { type: "single", topic: "英文·文法", q: "「I look forward to ______ you soon.」空格應填？", options: ["seen", "see", "saw", "seeing"], answer: 3,
      solution: "look forward to + Ving，用 seeing。" },
    { type: "single", topic: "英文·文法", q: "「The movie was so ______ that everyone cried.」空格應填？", options: ["to touch", "touched", "touching", "touch"], answer: 2,
      solution: "so + 形容詞（事物令人感動）用 -ing：touching。" },
    { type: "single", topic: "英文·字彙", q: "「generous」的中文意思為？", options: ["慷慨的", "平凡的", "嚴肅的", "靈活的"], answer: 0,
      solution: "generous 慷慨的、大方的。" },
    { type: "single", topic: "英文·字彙", q: "「It is important to protect the ______（環境）.」", options: ["government", "entertainment", "environment", "experiment"], answer: 2,
      solution: "environment 環境；Government 政府。" },
    { type: "single", topic: "英文·字彙", q: "「approximately」意為？", options: ["精確地", "絕對地", "大約", "證明"], answer: 2,
      solution: "approximately 大約、約略。" },
    { type: "single", topic: "英文·字彙", q: "下列何者為「（動）感激、欣賞」？", options: ["apply", "appreciate", "appear", "approach"], answer: 1,
      solution: "appreciate 感激、賞識；approach 接近；apply 申請。" },
    { type: "single", topic: "英文·文法", q: "「He ______ to the party if he had been invited.」（與過去事實相反的假設）", options: ["will come", "had come", "would have come", "would come"], answer: 2,
      solution: "與過去事實相反：would have + p.p.。" },
    { type: "single", topic: "英文·字彙", q: "「patient」作名詞時意為？", options: ["耐心", "專利", "病人（形容詞耐心）", "病人"], answer: 3,
      solution: "patient 可作名詞「病人」，亦作形容詞「有耐心的」。" },
    { type: "single", topic: "英文·答案", q: "「I can't ______（容忍）the noise anymore.」空格應填？", options: ["standed", "stand", "standing", "stands"], answer: 1,
      solution: "can't stand 無法忍受；情態動詞後接原形。" },
    { type: "multi", topic: "英文·文法", q: "下列哪些句子時態使用「現在完成式」？（多選）", options: ["She has visited Paris.", "He went home yesterday.", "They have finished.", "I have seen that movie."], answer: [0, 2, 3],
      solution: "has/have + p.p. 為現在完成式：visited、finished、seen；went 為過去式。" },
    { type: "multi", topic: "英文·字彙", q: "下列哪些是「形容詞」？（多選）", options: ["quickly", "happy", "comfortable", "beautiful"], answer: [1, 2, 3],
      solution: "beautiful、comfortable、happy 為形容詞；quickly 為副詞。" },
    { type: "multi", topic: "英文·文法", q: "下列哪些句子正確？（多選）", options: ["I am go home.", "We were watching TV.", "They are playing now.", "She is going to school."], answer: [1, 2, 3],
      solution: "「I am go home」應為 I am going home，故錯誤；其餘進行式用法正確。" },
    { type: "multi", topic: "英文·閱讀", q: "閱讀短文後選出正確選項（多選）：『Tom usually gets up at six and jogs in the park. He enjoys the fresh air in the morning.』下列何者正確？", options: ["Tom sleeps until noon.", "Tom jogs in the park.", "Tom runs in the morning.", "Tom likes the fresh air."], answer: [1, 2, 3],
      solution: "文中 Tom 早起慢跑（jog）、享受新鮮空氣；未提睡到中午。" },
    { type: "fill", topic: "英文·字彙", q: "「happy」的名詞形式為？（英文）", answerText: "happiness",
      solution: "happy（形）→ happiness（名）快樂。" },
    { type: "fill", topic: "英文·字彙", q: "「decide」的名詞形式為？（英文）", answerText: "decision",
      solution: "decide（動）→ decision（名）決定。" },
    { type: "fill", topic: "英文·文法", q: "「be動詞＋Ving」構成何種時態？", answerText: "進行式",
      solution: "be + Ving 為現在進行式（過去進行式看 be 的時態）。" },
    { type: "fill", topic: "英文·文法", q: "英文句子的基本結構「主詞＋＿＿＿＿＋受詞」為何？", answerText: "動詞",
      solution: "基本句型 S + V + O：主詞＋動詞＋受詞。" },
    { type: "calc", topic: "英文·文法", q: "將「go」改為「第三人稱單數現在式」。", answerText: "goes",
      solution: "go → goes（加 -es）。" },
    { type: "calc", topic: "英文·文法", q: "將「study」改為「現在分詞（Ving）」。", answerText: "studying",
      solution: "study 以 y 結尾，直接加 -ing → studying。" },
    { type: "single", topic: "英文·閱讀",
      passage: "閱讀短文：『Many students use smartphones every day. They use them to chat, search for information, and play games. However, too much screen time may be bad for their eyes and sleep.』",
      q: "根據上文，下列何者為作者的主要觀點？", options: ["手機百害無利", "手機使用有助學習但對眼睛有影響", "學生完全不應用手機", "遊戲有益身心"], answer: 1,
      solution: "文中肯定手機用途，但提醒過度使用對眼睛與睡眠的影響。" }
  ]
};

// 開學考各科目題數統計
const SUBJECT_KEYS = Object.keys(SUBJECT_QUESTIONS);
function getSubjectCounts() {
  const o = {};
  SUBJECT_KEYS.forEach(k => o[k] = SUBJECT_QUESTIONS[k].length);
  return o;
}
